---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: descheduler
  namespace: descheduler
spec:
  chart:
    spec:
      chart: descheduler
      version: '0.27.0'
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: descheduler
        namespace: flux-system
  install:
    createNamespace: true
  values:
    image:
      repository: registry.k8s.io/descheduler/descheduler
      tag: v0.27.1
    schedule: '*/10 * * * *'
    suspend: false
    serviceMonitor:
      enabled: true
  interval: 10m0s
