---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: descheduler
  namespace: descheduler
spec:
  chart:
    spec:
      chart: descheduler
      version: '0.30.1'
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: descheduler
        namespace: flux-system
  install:
    createNamespace: true
  values:
    image:
      repository: registry.k8s.io/descheduler/descheduler
      tag: v0.30.1
    schedule: '*/10 * * * *'
    suspend: false
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: node-role.kubernetes.io/control-plane
                  operator: Exists
    tolerations:
      - key: node-role.kubernetes.io/control-plane
        operator: Exists
        effect: NoSchedule
    serviceMonitor:
      enabled: true
  interval: 10m0s
