---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: uptime-kuma
  namespace: uptime-kuma
spec:
  chart:
    spec:
      chart: uptime-kuma
      version: '1.0.2'
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: pascaliske
        namespace: flux-system
  install:
    createNamespace: true
  values:
    image:
      repository: louislam/uptime-kuma
      tag: 1.20.1-alpine
    serviceMonitor:
      enabled: true
    ingressRoute:
      create: true
      entryPoints:
        - https
      rule: Host(`status.${DOMAIN_EXTERNAL}`)
      middlewares:
        - name: auth-external
          namespace: traefik
        - name: security
          namespace: traefik
        - name: optimizations
          namespace: traefik
        - name: error-pages
          namespace: traefik-errors
    certificate:
      create: true
      dnsNames:
        - status.${DOMAIN_EXTERNAL}
      issuerRef:
        kind: ClusterIssuer
        name: lets-encrypt-production
    env:
      - name: TZ
        value: ${TIMEZONE}
      - name: PGID
        value: ${GID}
      - name: PUID
        value: ${UID}
    persistentVolumeClaim:
      storageClassName: local-path
    resources:
      limits:
        cpu: 256m
        memory: 1Gi
      requests:
        cpu: 128m
        memory: 512Mi
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: k8s.pascaliske.dev/location
                  operator: In
                  values:
                    - public
    tolerations:
      - key: k8s.pascaliske.dev/location
        operator: Equal
        value: public
        effect: NoSchedule
  interval: 10m0s
