# configure k3s
- name: Configure k3s
  become: true
  block:
    - name: Ensure configuration directory exists
      file:
        path: /etc/rancher/k3s
        state: directory
    - name: Create configuration file
      template:
        src: '{{ role_name }}/config.yaml.j2'
        dest: /etc/rancher/k3s/config.yaml

# install k3s
- name: Install k3s on workers
  shell:
    cmd: curl -sfL https://get.k3s.io | INSTALL_K3S_VERSION="{{ k3s_worker_version }}" K3S_URL="https://{{ k3s_worker_registration_url }}:6443" K3S_TOKEN="{{ k3s_worker_registration_token }}" sh -
  changed_when: true
