# configure k3s
- name: Configure k3s
  become: true
  block:
    - name: Ensure configuration directory exists
      file:
        path: /etc/rancher/k3s
        state: directory
    - name: Create configuration file
      template:
        src: '{{ role_name }}/config.yaml.j2'
        dest: /etc/rancher/k3s/config.yaml

# install k3s
- name: Install k3s on workers
  changed_when: true
  shell:
    cmd: '{{ item }}'
  loop:
    # renovate: datasource=github-releases depName=k3s-io/k3s
    - curl -sfL https://get.k3s.io | INSTALL_K3S_VERSION="v1.29.1+k3s2" K3S_URL="https://{{ k3s_worker_url }}:6443" K3S_TOKEN="{{ k3s_worker_token }}" sh -
