---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: gitlab
  namespace: gitlab
spec:
  chart:
    spec:
      chart: gitlab
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: pascaliske
        namespace: flux-system
  install:
    createNamespace: true
  values:
    image:
      repository: gitlab/gitlab-ce
      tag: 15.6.2-ce.0
    env:
      - name: TZ
        value: ${TIMEZONE}
    configMap:
      create: false
      existingConfigMap: gitlab-config
    persistentVolumeClaims:
      secrets:
        storageClassName: local-path
      storage:
        storageClassName: local-path
    healthCheck:
      whitelist:
        - 127.0.0.1
        - 10.42.2.1
    backups:
      hostPath: ${PATH_HOME}/gitlab/backups
      cronJob:
        enabled: true
        schedule: '0 3 * * 1'
        successfulJobsHistoryLimit: 1
        failedJobsHistoryLimit: 1
    resources: {}
      # limits:
      #   cpu: 100m
      #   memory: 128Mi
      # requests:
      #   cpu: 100m
      #   memory: 128Mi
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: k8s.pascaliske.dev/location
                  operator: In
                  values:
                    - public
    tolerations:
      - key: k8s.pascaliske.dev/location
        operator: Equal
        value: public
        effect: NoSchedule
  interval: 10m0s
