---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: paperless
  namespace: paperless
spec:
  chart:
    spec:
      chart: paperless
      version: '4.0.2'
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: pascaliske
        namespace: flux-system
  install:
    createNamespace: true
  values:
    image:
      repository: ghcr.io/paperless-ngx/paperless-ngx
      tag: 1.13.0
    ingressRoute:
      create: true
      entryPoints:
        - https
      rule: Host(`docs.${DOMAIN_EXTERNAL}`)
      middlewares:
        - name: auth-external
          namespace: traefik
        - name: security
          namespace: traefik
        - name: optimizations
          namespace: traefik
        - name: error-pages
          namespace: traefik-errors
    certificate:
      create: true
      dnsNames:
        - docs.${DOMAIN_EXTERNAL}
      issuerRef:
        kind: ClusterIssuer
        name: lets-encrypt-production
    env:
      - name: TZ
        value: ${TIMEZONE}
      - name: USERMAP_UID
        value: '${UID}'
      - name: USERMAP_GID
        value: '${GID}'
      - name: PAPERLESS_URL
        value: https://docs.${DOMAIN_EXTERNAL}
      - name: PAPERLESS_ADMIN_USER
        value: ${PAPERLESS_ADMIN_USER}
      - name: PAPERLESS_ADMIN_PASSWORD
        value: ${PAPERLESS_ADMIN_PASSWORD}
      - name: PAPERLESS_ADMIN_MAIL
        value: ${PAPERLESS_ADMIN_EMAIL}
      - name: PAPERLESS_ENABLE_HTTP_REMOTE_USER
        value: 'true'
      - name: PAPERLESS_LOGOUT_REDIRECT_URL
        value: https://auth.${DOMAIN_EXTERNAL}/logout?rd=https://docs.${DOMAIN_EXTERNAL}
      - name: PAPERLESS_REDIS
        value: redis://redis.redis.svc.cluster.local:6379
      - name: PAPERLESS_ALLOWED_HOSTS
        value: '*'
      - name: PAPERLESS_OCR_LANGUAGE
        value: deu
      - name: PAPERLESS_IGNORE_DATES
        value: ${PAPERLESS_IGNORE_DATES}
      - name: PAPERLESS_ENABLE_UPDATE_CHECK
        value: 'true'
      - name: PAPERLESS_ENABLE_COMPRESSION
        value: 'false'
    secret:
      create: true
      values:
        PAPERLESS_SECRET_KEY: ${PAPERLESS_SECRET_KEY}
    persistentVolumeClaim:
      size: 10Gi
      storageClassName: local-path
    consumption:
      enabled: true
      type: hostPath
      hostPath:
        type: Directory
        path: ${PATH_HOME}/paperless/import
    export:
      enabled: true
      type: hostPath
      hostPath:
        type: Directory
        path: ${PATH_HOME}/paperless/export
      cronJob:
        enabled: true
        schedule: '0 4 * * 1'
        successfulJobsHistoryLimit: 1
        failedJobsHistoryLimit: 1
    trash:
      enabled: true
      type: hostPath
      hostPath:
        type: Directory
        path: ${PATH_HOME}/paperless/trash
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: k8s.pascaliske.dev/location
                  operator: In
                  values:
                    - public
    tolerations:
      - key: k8s.pascaliske.dev/location
        operator: Equal
        value: public
        effect: NoSchedule
  interval: 10m0s
