---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: clickhouse
  namespace: clickhouse
spec:
  chart:
    spec:
      chart: clickhouse
      version: '0.4.0'
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: pascaliske
        namespace: flux-system
  values:
    image:
      registry: docker.io
      repository: clickhouse/clickhouse-server
      tag: 26.1.1.912-alpine
    env:
      - name: TZ
        value: ${TIMEZONE}
      - name: CLICKHOUSE_SKIP_USER_SETUP
        value: '1'
  interval: 10m0s
