---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: cloudnative-pg-charts
  namespace: flux-system
spec:
  interval: 10m0s
  url: https://cloudnative-pg.github.io/charts
