{
 "title": "Ingress",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(traefik_config_reloads_total, instance)"
    }
   },
   {
    "name": "protocol",
    "label": "Protocol",
    "query": {
     "query": "label_values(traefik_service_requests_total, protocol)"
    }
   },
   {
    "name": "service",
    "label": "Service",
    "query": {
     "query": "label_values(traefik_service_requests_total{instance=~\"[[instance]]\"}, exported_service)"
    }
   },
   {
    "name": "interval",
    "label": "Interval",
    "query": "5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 11, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - process_start_time_seconds{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Config Reloads",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 11, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "traefik_config_reloads_total{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Config Reload Success",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "traefik_config_last_reload_success{instance=\"$instance\"} <= 0 or time() - traefik_config_last_reload_success{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Config Reload Failure",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "traefik_config_last_reload_failure{instance=~\"$instance\"} <= 0 or time() - traefik_config_last_reload_failure{instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Successful Responses",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(traefik_service_requests_total{code=~\"(2|3)[0-9]{2}\",instance=~\"$instance\", exported_service=~\"$service\", protocol=~\"$protocol\"}[$interval]))",
     "legendFormat": "Successful Responses"
    }
   ]
  },
  {
   "title": "Server Errors",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(traefik_service_requests_total{code=~\"5[0-9]{2}\",instance=~\"$instance\", exported_service=~\"$service\", protocol=~\"$protocol\"}[$interval]))",
     "legendFormat": "Errors"
    }
   ]
  },
  {
   "title": "Client Errors",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(traefik_service_requests_total{code=~\"4[0-9]{2}\",instance=~\"$instance\", exported_service=~\"$service\", protocol=~\"$protocol\"}[$interval]))",
     "legendFormat": "Errors"
    }
   ]
  },
  {
   "title": "Average Response Time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(traefik_entrypoint_request_duration_seconds_sum{instance=~\"$instance\"}[$interval])) / sum(rate(traefik_entrypoint_requests_total{instance=~\"$instance\"}[$interval]))",
     "legendFormat": "Response Time"
    }
   ]
  },
  {
   "title": "Total requests by service",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(traefik_service_requests_total{instance=~\"$instance\", exported_service=~\"$service\"}[$interval])) by (exported_service)",
     "legendFormat": "{{ service }}"
    }
   ]
  },
  {
   "title": "Avg. response time by service",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(traefik_service_request_duration_seconds_sum{instance=~\"$instance\",exported_service=~\"$service\",protocol=~\"$protocol\"}[$interval])) by (exported_service) / sum(rate(traefik_service_request_duration_seconds_count{instance=~\"$instance\",exported_service=~\"$service\",protocol=~\"$protocol\"}[$interval])) by (exported_service)",
     "legendFormat": "{{ service }}"
    }
   ]
  },
  {
   "title": "Open Connections",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(traefik_service_open_connections{instance=~\"$instance\", exported_service=~\"$service\"}) by (method)",
     "legendFormat": "{{ method }}"
    }
   ]
  }
 ]
}