---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: gitlab
  namespace: gitlab
spec:
  chart:
    spec:
      chart: gitlab
      version: '4.0.0'
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: pascaliske
        namespace: flux-system
  values:
    image:
      repository: gitlab/gitlab-ce
      tag: 18.8.4-ce.0
    env:
      - name: TZ
        value: ${TIMEZONE}
    configMap:
      create: false
      existingConfigMap: gitlab-config
    healthCheck:
      whitelist:
        - 127.0.0.0/8
        - 10.42.0.0/16
        - 10.0.2.0/24
    backups:
      enabled: true
      type: pvc
      persistentVolumeClaim:
        claimName: gitlab-backups
      cronJob:
        enabled: false
        schedule: '0 3 * * 1'
        successfulJobsHistoryLimit: 1
        failedJobsHistoryLimit: 1
    registryGarbageCollection:
      cronJob:
        enabled: false
    extraObjects:
      - apiVersion: v1
        kind: PersistentVolumeClaim
        metadata:
          name: gitlab-backups
          namespace: gitlab
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 5Gi
          volumeMode: Filesystem
  interval: 10m0s
