{
 "title": "Nodes",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "interval",
    "label": "Interval",
    "query": "5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "node",
    "label": "Node",
    "query": {
     "query": "label_values(node_load1, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (irate(node_cpu_seconds_total{instance=~\"$node\",mode=\"idle\"}[$interval])) * 100)",
     "legendFormat": "Usage"
    },
    {
     "expr": "avg by (instance) (irate(node_cpu_seconds_total{instance=~\"$node\",mode=\"iowait\"}[$interval])) * 100",
     "legendFormat": "IOwait"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "avg by (instance) (node_hwmon_temp_celsius{instance=~\"$node\"})",
     "legendFormat": "Actual"
    },
    {
     "expr": "avg by (instance) (avg_over_time(node_hwmon_temp_celsius{instance=~\"$node\"}[$interval]))",
     "legendFormat": "Average"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_time_seconds{instance=~\"$node\"} - node_boot_time_seconds{instance=~\"$node\"}"
    }
   ]
  },
  {
   "title": "Load 1",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 18, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_load1{instance=~\"$node\"}) by (node) / count(node_cpu_seconds_total{instance=~\"$node\",mode=\"idle\"}) by (node) * 100"
    }
   ]
  },
  {
   "title": "Load 5",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 20, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_load5{instance=~\"$node\"}) by (node) / count(node_cpu_seconds_total{instance=~\"$node\",mode=\"idle\"}) by (node) * 100"
    }
   ]
  },
  {
   "title": "Load 15",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 22, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_load15{instance=~\"$node\"}) by (node) / count(node_cpu_seconds_total{instance=~\"$node\",mode=\"idle\"}) by (node) * 100"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * (1 - ((node_memory_MemFree_bytes{instance=~\"$node\"} + node_memory_Cached_bytes{instance=~\"$node\"} + node_memory_Buffers_bytes{instance=~\"$node\"}) / node_memory_MemTotal_bytes{instance=~\"$node\"}))",
     "legendFormat": "Actual"
    },
    {
     "expr": "100 * (1 - ((avg_over_time(node_memory_MemFree_bytes{instance=~\"$node\"}[$interval]) + avg_over_time(node_memory_Cached_bytes{instance=~\"$node\"}[$interval]) + avg_over_time(node_memory_Buffers_bytes{instance=~\"$node\"}[$interval])) / avg_over_time(node_memory_MemTotal_bytes{instance=~\"$node\"}[$interval])))",
     "legendFormat": "Average"
    }
   ]
  },
  {
   "title": "Processes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "node_procs_running{instance=~\"$node\"}",
     "legendFormat": "Running"
    },
    {
     "expr": "node_procs_blocked{instance=~\"$node\"}",
     "legendFormat": "Blocked by I/O"
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{instance=~\"$node\",mountpoint=\"/\"} * 100) / node_filesystem_size_bytes{instance=~\"$node\",mountpoint=\"/\"})",
     "legendFormat": "Root"
    },
    {
     "expr": "100 - ((node_filesystem_avail_bytes{instance=~\"$node\",mountpoint=\"/var/log\"} * 100) / node_filesystem_size_bytes{instance=~\"$node\",mountpoint=\"/var/log\"})",
     "legendFormat": "Logs"
    }
   ]
  },
  {
   "title": "Network I/O",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "sum by (node, device) (rate(node_network_receive_bytes_total{instance=~\"$node\",device=\"eth0\"}[$interval])) * 8",
     "legendFormat": "{{ device }}-in"
    },
    {
     "expr": "sum by (node, device) (rate(node_network_transmit_bytes_total{instance=~\"$node\",device=\"eth0\"}[$interval])) * 8",
     "legendFormat": "{{ device }}-out"
    }
   ]
  },
  {
   "title": "Network Packets",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (node, device) (rate(node_network_receive_packets_total{instance=~\"$node\",device=\"eth0\"}[$interval]))",
     "legendFormat": "{{ device }}-in"
    },
    {
     "expr": "sum by (node, device) (rate(node_network_transmit_packets_total{instance=~\"$node\",device=\"eth0\"}[$interval]))",
     "legendFormat": "{{ device }}-out"
    }
   ]
  },
  {
   "title": "Network Dropped Packets",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (node, device) (rate(node_network_receive_drop_total{instance=~\"$node\",device=\"eth0\"}[$interval]))",
     "legendFormat": "{{ device }}-in"
    },
    {
     "expr": "sum by (node, device) (rate(node_network_transmit_drop_total{instance=~\"$node\",device=\"eth0\"}[$interval]))",
     "legendFormat": "{{ device }}-out"
    }
   ]
  }
 ]
}