{
 "title": "Containers",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "service",
    "label": "Service",
    "query": {
     "query": "label_values(container_memory_usage_bytes, container_label_com_docker_compose_service)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Container CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg by (name) (irate(container_cpu_usage_seconds_total{image!=\"\",name=~\"$service\"}[5m])) * 100",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Container Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "avg by (name) (container_memory_usage_bytes{image!=\"\",name=~\"$service\"})",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Container Disk Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "avg by (name) (container_fs_usage_bytes{image!=\"\",name=~\"$service\"})",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Container Restarts",
   "type": "table",
   "gridPos": { "h": 16, "w": 8, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "targets": [
    {
     "expr": "time() - min by (name, instance) (container_start_time_seconds{image!=\"\"})",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Container Updates",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 16 },
   "targets": [
    { "expr": "watchtower_containers_scanned", "legendFormat": "Scanned" },
    { "expr": "watchtower_containers_updated", "legendFormat": "Updated" },
    { "expr": "watchtower_containers_failed", "legendFormat": "Failed" }
   ]
  }
 ]
}