apiVersion: v1
kind: Secret
metadata:
    name: netbox-admin
    namespace: netbox
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:Q9BRUCaB+vnE6g==,iv:cx9xTOeBplR4mxCBuZKC+HUbjPtO9fnaSIxLln01e78=,tag:RN++xpRtobGi+OjUPokYCg==,type:str]
    password: ENC[AES256_GCM,data:g4yrCqBoqn8lg/aSfS2rSKspbVCQ5+cMy/7+dWLZsFjNBgGbkH/bAJEF,iv:yNEl7yBXv+QfqbkB6BDISRV1bn/sOm+rpNiHkgF+AAE=,tag:L1NxeazBbUhGLkT/ldd2nw==,type:str]
    email: ENC[AES256_GCM,data:jH8XzXCC3RzZl/BwMfJWTZkkXg==,iv:gv7T/c+K7AuKo4/CTopKG6+BLogEa10gRApJBXGq5pk=,tag:g6kaK9O5cGUhBK4xmwX9TQ==,type:str]
    api_token: ENC[AES256_GCM,data:3oWoynHWCnQDYXslMEVHXJv2JgWo7D1vXA7MRlCfY4zGMB5C4WGDNEryiXJB1iMt,iv:+0N6WxfeqsOTvjXTGnMyqUpJFajQV1q4GJPqbh+ftPA=,tag:UTxs03o0Aae7paQ1iJUF4A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiMW45YUtsQlNQcGl3RlNV
            dG5qTmd2TUg1dGs4YTJpY3loQlRQK1NGZnh3CmtjOU9vU2NsamNMeTJNMTl6eTNU
            dHZYWkhuN2dVSU13MVFpaEYrV3J3UXcKLS0tIGt2dVByTzlCYjg0MXNRSGtkRGta
            MnQwV0xrVkxLaFZQQlFIZWkxL0svUGcKbhfUPn9Xx/ndPewJ+AWAZkOKsMaYklt0
            mkh9mbXt6OwEMtBEuNqXr+AmoQ/q9FeFJtm9941Nrmzuw3ZbOYqZKg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1znmsndwgl8f4wxn5ydl3f0gkcvcz5uqd5zeervevmmsaygwvrfysgx8xpp
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-14T14:51:13Z"
    mac: ENC[AES256_GCM,data:7Th1rX0ufuoveE++GOb5FWkbezQ3CtJpThe+YeGlnbBlfnHDY25ETW41Mx0Iwfv5t2S3J1fE+LRhAAscfDNmtFTe+1jCGivUZSLhXP4EfkL4ZcfKc/itofSnVMOOJL/jmLVALbn+fcr/+ILyxZr+aYtQrm4zvvwxQZSidAL6cj4=,iv:YbMnrbwOUrth6+z/cuOaSzj1aolYVSvx/3L3PW407ic=,tag:EHOWPLEnuhbXuKqgf+MQnQ==,type:str]
    version: 3.13.3
