apiVersion: v1
kind: Secret
metadata:
    name: netbox-api-secrets
    namespace: netbox
type: Opaque
stringData:
    secret_key: ENC[AES256_GCM,data:JQflwGkXmh8A3CE0RMHsXeJMzHbc/xDWxBRy59yY8M3rbYPXImlGlo+cOANAQZyQXR4=,iv:TB8aPoklINkM6tpaZa52/1kE4FjvgIGQO6sm/3+wxGE=,tag:rYgW+H2lgR9A8PJlnYUojw==,type:str]
    api_token_peppers: ENC[AES256_GCM,data:S9TCqGYni2zozGvenYwVDECb1O6NWl4vU1uDqIzCC2OOOAG7tFThpDq+uu5/U9rYn9+3Hr/h0zzb2qHuXWty,iv:NMyL3c1CDtFmdeN82W8pxFDfmkroUnEvCpur6e7gkrQ=,tag:87S5DrfGy56+pD66YxhONw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1UWdLS0xVYTZ5TlljdUVC
            aWtDR1dsT2xoZzRRa2oyNjZBUWs0dkZ2eFJNCjVHa1REYjhFL1FvUkErWXdhSjJw
            dEVYYXdKTDdCQm01Z3J1Njd3MFNqNEkKLS0tIFRqVkQ2ZXM0RDhTNEh2cnVyV05T
            dTJObVBnZ1MrRUF4Tm1VN1ZxR3hKYm8KROL1mpySe/xZtKC8B76f30f605A43lHJ
            kaRzG4BIo12hG9+bU1Fv8kLbhLEXPYdNAZNmWMit+ILIbcd3NFP7iQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1znmsndwgl8f4wxn5ydl3f0gkcvcz5uqd5zeervevmmsaygwvrfysgx8xpp
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-14T11:36:10Z"
    mac: ENC[AES256_GCM,data:xcWYkLVkFII27EwGv1a/QjshQ70Be+t4ynSa98XU7pptXyS121M3Ga4MkkVBArm1KUlg7jYeoiQpAW4PhExbrvYx63VN3gPgCGUbGGsXMhz3hLBJVBYMGpSnj4NanRFGni9hBE0YKK7XOGLmxROmonIDZ2q/0ndu62YMsWCFJTY=,iv:AAJizK1+LIHTtTepU28whyUuLym48tdxeONnFRXdmV0=,tag:kZNckBXaEUiQm5DMq9pA+g==,type:str]
    version: 3.13.3
