apiVersion: v1
kind: Secret
metadata:
    name: netbox-redis-credentials
    namespace: netbox
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:J5GqpOi7ea7GMO36ohJ04Il0TtlVNMZBGEqvo8SuBOQUgUAaz7zXlRtv,iv:NG+9hpn+SbLfYtiJZxzA13BCQBCQtf8mMankfLskbLI=,tag:JDJYLNIjOpqsBwqGnbZfhw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUUVdoNFVtVklkSmJUKzI0
            QWh1cE1pQWs5REpzZ0dyMHhUL2hLNjgvaEZVCmdRVURKbUg4azI1aFk5dFNrdW9V
            WFJFczg1bXdteDhWRDJGL2s2Ty9BL3MKLS0tIHJ0eWNWQXBlTElrcWFrS256cGs3
            RkFoZlE2RnNhL3BmaVVaZk9rd1NjcHcKf56Gv1sT3pqSn4mokZF36lu+nBR7i5V9
            Jvz+DVNLka5Nm/4GGq8+mLQGJ6jLTVzDnDL4pTv0wL2fYZE/N8y99Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1znmsndwgl8f4wxn5ydl3f0gkcvcz5uqd5zeervevmmsaygwvrfysgx8xpp
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-14T11:45:02Z"
    mac: ENC[AES256_GCM,data:pvNOKq0l5fdnREIi6qlqbe5KLIhlkt++U5eF/Md3/YOdpQyk1H7p7xojcwWgxVTUosbMEii9UPbB+O1+c2TtSi/BOKQzmLQ1/ydVrw2yIn3aFmsqjqJkul3dMy3p4rAd9uDuoe5dpfagSkI+JqsMl4okOeV4rNF9li+9B0xhJpQ=,iv:LZWyQglWgFn/7hBjaV5JTwvgk6agZbdtAUhmLgeLKq0=,tag:bEW+9JZCz5fDP0o586/9Zw==,type:str]
    version: 3.13.3
