apiVersion: v1
kind: Secret
metadata:
    name: netbox-smtp-credentials
    namespace: netbox
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:uXThpTGT3s7EQ9Jf3TU1UlVSKyW4njVr5Gr7Kmr4Xth6z+14U9xl+aw8,iv:L4XfLNKUia53mcpbfP08mu4gN+vpXd9KbWyv5GM1huw=,tag:LUPO1/MjfPPjIieAHLj/eQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXemhnbXVBeHZUYUp1TnBu
            TmhhOTY2UzdZQWRMdWJ2dW95bCtzL01nQ2tJCkx5bitUV3YvSmRvRldDT2RQd1B5
            azVyLyswdG0zaHJxWm5xZm1UTVRGL3cKLS0tIGYrSWJ2bW5oRW8vaktTR0JFdnVr
            TDJqcmZab1lYaDVxSjEyUHpnbFJqdE0Kn5+fO8PNF3yL0uAwhaqdyyOoUc+Lbqzk
            yIGAvoDK8RrHxJ06gNIfPCuwnBa+6CVxGKoOR3R45xRFcO0rBT7+kw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1znmsndwgl8f4wxn5ydl3f0gkcvcz5uqd5zeervevmmsaygwvrfysgx8xpp
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-14T11:48:15Z"
    mac: ENC[AES256_GCM,data:76oaIan83ATlp6N/hZNjdVo8M78T5uHhG4dR2BdKSfiu2IT3tzjCtvMcl++JJQfT9o4Dx6DQPsURVpleyO2HkBOm1un++e1sMabLtnxw6TLWs8r0rl+nvCFhHBVoE5m2WJboVQtuTr7IlAPjocj45A8pWTC6HfsnDQrElik5V8A=,iv:doarLNx+qHM1OdmzsghRaXcmQQ+HjwMf1EBLTdGHOvo=,tag:zZyWpvlArIuXR01JKN7UUA==,type:str]
    version: 3.13.3
