---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: silence-operator
  namespace: silence-operator
spec:
  chart:
    spec:
      chart: silence-operator
      version: '0.16.1'
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: giantswarm
        namespace: flux-system
  install:
    crds: Skip
  upgrade:
    crds: Skip
  values:
    image:
      repository: quay.io/giantswarm/silence-operator
      tag: '0.16.1'
    alertmanagerAddress: 'http://kube-prometheus-stack-alertmanager.monitoring.svc.cluster.local:9093'
    networkPolicy:
      enabled: true
    crds:
      install: false
  interval: 10m0s
