---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: node-feature-discovery
  namespace: kube-system
spec:
  chart:
    spec:
      chart: node-feature-discovery
      version: '0.18.2'
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: node-feature-discovery
        namespace: flux-system
  values: # defaults: https://github.com/kubernetes-sigs/node-feature-discovery/blob/master/deployment/helm/node-feature-discovery/values.yaml
    image:
      repository: gcr.io/k8s-staging-nfd/node-feature-discovery
      tag: 'v0.18.2'
    prometheus:
      enable: true
  interval: 10m0s
