{
 "title": "Plausible Analytics",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "site",
    "label": "Site",
    "query": {
     "query": "label_values(plausible_visitors, site_id)"
    }
   }
  ]
 },
 "panels": [
  { "title": "$site", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "site" },
  {
   "title": "Visitors",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "plausible_visitors{site_id=~\"$site\"}",
     "legendFormat": "{{site_id}}"
    }
   ]
  },
  {
   "title": "Visit Duration",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "targets": [
    {
     "expr": "plausible_visit_duration{site_id=~\"$site\"}",
     "legendFormat": "{{site_id}}"
    }
   ]
  },
  {
   "title": "Page VIews",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "plausible_pageviews{site_id=~\"$site\"}",
     "legendFormat": "{{site_id}}"
    }
   ]
  },
  {
   "title": "Bounce Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "plausible_bounce_rate{site_id=~\"$site\"}",
     "legendFormat": "{{site_id}}"
    }
   ]
  }
 ]
}