{
 "title": "Climate",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "room",
    "label": "Room",
    "query": {
     "query": "label_values(homeassistant_sensor_temperature_celsius{friendly_name=~\"(.*) (C|c)limate (T|t)emperature\"}, friendly_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 21, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "label_replace(homeassistant_sensor_temperature_celsius{friendly_name=~\"$room Climate Temperature\"}, \"short_name\", \"$1\", \"friendly_name\", \"(.*) (C|c)limate (T|t)emperature\")",
     "legendFormat": "{{ short_name }}"
    }
   ]
  },
  {
   "title": "Average Temperature",
   "type": "stat",
   "gridPos": { "h": 20, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "label_replace(homeassistant_sensor_temperature_celsius, \"short_name\", \"$1\", \"friendly_name\", \"(.*) (C|c)limate (T|t)emperature\")",
     "legendFormat": "{{short_name}}"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 21, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "label_replace(homeassistant_sensor_humidity_percent{friendly_name=~\"$room Climate Humidity\"}, \"short_name\", \"$1\", \"friendly_name\", \"(.*) (C|c)limate (H|h)umidity\")",
     "legendFormat": "{{ short_name }}"
    }
   ]
  },
  {
   "title": "Pressure",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 21, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "pressurehpa" } },
   "targets": [
    {
     "expr": "label_replace(homeassistant_sensor_pressure_hpa{friendly_name=~\"$room Climate Pressure\"}, \"short_name\", \"$1\", \"friendly_name\", \"(.*) (C|c)limate (P|p)ressure\")",
     "legendFormat": "{{ short_name }}"
    }
   ]
  }
 ]
}