---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: metallb
  namespace: metallb-system
spec:
  chart:
    spec:
      chart: metallb
      version: '0.15.3'
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: metallb
        namespace: flux-system
  values: # defaults: https://github.com/metallb/metallb/blob/main/charts/metallb/values.yaml
    prometheus:
      rbacPrometheus: false
      serviceMonitor:
        enabled: true
      prometheusRule:
        enabled: true
    speaker:
      frr:
        enabled: false
    crds:
      enabled: true
  interval: 10m0s
