---
# renovate: datasource=github-releases depName=k3s-io/k3s
k3s_worker_version: v1.29.1+k3s2
k3s_worker_ip: ''
k3s_worker_ip_tailscale: ''
k3s_worker_registration_url: ''
k3s_worker_registration_token: ''
k3s_worker_labels: []
k3s_worker_taints: []
