# yaml-language-server: $schema=https://json.schemastore.org/yamllint.json
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgresql
  namespace: paperless
spec:
  instances: 3
  imageName: ghcr.io/cloudnative-pg/postgresql:18.1
  primaryUpdateStrategy: unsupervised
  storage:
    size: 1Gi
  superuserSecret:
    name: postgresql-superuser
  bootstrap:
    initdb:
      database: paperless
      owner: paperless
      secret:
        name: postgresql-user
  monitoring:
    enablePodMonitor: true
