apiVersion: v1
kind: Secret
metadata:
    name: postgresql-user
    namespace: paperless
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:YmrmUq5DwBw4,iv:t2YToSTdoMspMwFHbT5O9XZF/xDAsjmeWDHEQRVJ48Y=,tag:q5AI3U/iuESenJ3k7Ye85w==,type:str]
    password: ENC[AES256_GCM,data:fDZVK7P9TQjdUYrL/le/ITSP4z0fwgIFWuEJRnOkpaAqer3xuBnSieOn,iv:lm/g4WCaXIYLy1jHALT3ohXDehyhi0tCt1uQ6XkUD3U=,tag:LY9snSbiz2LZ9toWhBE1Tw==,type:str]
sops:
    age:
        - recipient: age1znmsndwgl8f4wxn5ydl3f0gkcvcz5uqd5zeervevmmsaygwvrfysgx8xpp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBadEhJbUVocis0L1hBSm9S
            QldacHRxSmswWnFXNWw2ZTJjYmN5eVJ0TlRJCjBBVXlzWkNFMmxjUTRkcmxEQkVx
            U1Q1dWJzNVlqalJYQ0N2Q3lmSW5QQU0KLS0tIENoeWhmNEpPbFRycUlCWFVzTFVz
            NDI0WkRwVEExMXZGeldheGFqYkk3SEkK+QmL2KC2Q7J4aBoDxXX6x6Wy54aXUKRG
            kBsbpQGfrClwFodywKlfAXLU4OCWYcrJ8hgqvKJrMX8SXGE1Hg8SrA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-08T10:07:47Z"
    mac: ENC[AES256_GCM,data:Q5nNIW3RZ6fC0ON7VsU28g62NESXwuj8IE/S76Q5aCYnrqrXfl8rsAJ1rAeh/bVLCqA1sYJGF8ePgOOBk4TClEtLLclj3/gsci2g+8+GXbHCMj1oh8NqW6sYJJXQVotWHC86Le1DWWUKgsyAxjYfQ1DjuKU9CeZXSmKNKeE5Utc=,iv:pyduiwudYbwM1mJlpOewwtXOBXoAL2A4KQPE66Gz070=,tag:eiQrU4jTavmhi/+PGOobSA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
