---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: authelia
  namespace: flux-system
spec:
  url: oci://ghcr.io/authelia/chartrepo/authelia
  interval: 10m0s
  ref:
    tag: '0.11.20'
  layerSelector:
    mediaType: 'application/vnd.cncf.helm.chart.content.v1.tar+gzip'
  # verify:
  #   provider: cosign
  #   matchOIDCIdentity:
  #     - issuer: '^https://token.actions.githubusercontent.com$'
  #       subject: '^https://github.com/authelia/chartrepo.*$'
