---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: cert-manager
  namespace: flux-system
spec:
  url: oci://quay.io/jetstack/charts/cert-manager
  interval: 10m0s
  ref:
    tag: 'v1.21.1'
  layerSelector:
    mediaType: 'application/vnd.cncf.helm.chart.content.v1.tar+gzip'
  # verify:
  #   provider: cosign
  #   matchOIDCIdentity:
  #     - issuer: '^https://token.actions.githubusercontent.com$'
  #       subject: '^https://github.com/cert-manager/cert-manager.*$'
