---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization.json
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - authelia.yaml
  - cert-manager.yaml
  - clickhouse-operator.yaml
  - cloudflare-exporter.yaml
  - cloudnative-pg.yaml
  - crowdsec.yaml
  - descheduler.yaml
  - gitlab.yaml
  - johanneskastl.yaml
  - k8s-at-home.yaml
  - kube-prometheus-stack.yaml
  - kured.yaml
  - local-path-provisioner.yaml
  - loki.yaml
  - metallb.yaml
  - node-feature-discovery.yaml
  - node-problem-detector.yaml
  - pascaliske.yaml
  - redis-operator.yaml
  - silence-operator.yaml
  - tailscale.yaml
  - traefik.yaml
  - tuppr.yaml
  - vector.yaml
  - velero.yaml
