---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: local-path-provisioner
  namespace: flux-system
spec:
  url: oci://ghcr.io/rancher/local-path-provisioner/charts/local-path-provisioner
  interval: 10m0s
  ref:
    tag: '0.0.37'
  layerSelector:
    mediaType: 'application/vnd.cncf.helm.chart.content.v1.tar+gzip'
  # verify:
  #   provider: cosign
  #   matchOIDCIdentity:
  #     - issuer: '^https://token.actions.githubusercontent.com$'
  #       subject: '^https://github.com/rancher/local-path-provisioner.*$'
