---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: metallb
  namespace: flux-system
spec:
  url: oci://quay.io/metallb/chart/metallb
  interval: 10m0s
  ref:
    tag: '0.16.1'
  layerSelector:
    mediaType: 'application/vnd.cncf.helm.chart.content.v1.tar+gzip'
  # verify:
  #   provider: cosign
  #   matchOIDCIdentity:
  #     - issuer: '^https://token.actions.githubusercontent.com$'
  #       subject: '^https://github.com/metallb/metallb.*$'
