---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: node-problem-detector
  namespace: flux-system
spec:
  url: oci://ghcr.io/deliveryhero/helm-charts/node-problem-detector
  interval: 10m0s
  ref:
    tag: '2.4.1'
  layerSelector:
    mediaType: 'application/vnd.cncf.helm.chart.content.v1.tar+gzip'
  # verify:
  #   provider: cosign
  #   matchOIDCIdentity:
  #     - issuer: '^https://token.actions.githubusercontent.com$'
  #       subject: '^https://github.com/deliveryhero/helm-charts.*$'
