---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: traefik
  namespace: flux-system
spec:
  url: oci://ghcr.io/traefik/helm/traefik
  interval: 10m0s
  ref:
    tag: '41.2.0'
  layerSelector:
    mediaType: 'application/vnd.cncf.helm.chart.content.v1.tar+gzip'
  # verify:
  #   provider: cosign
  #   matchOIDCIdentity:
  #     - issuer: '^https://token.actions.githubusercontent.com$'
  #       subject: '^https://github.com/traefik/traefik.*$'
