---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: tuppr
  namespace: flux-system
spec:
  url: oci://ghcr.io/home-operations/charts/tuppr
  interval: 10m0s
  ref:
    tag: '0.5.3'
  layerSelector:
    mediaType: 'application/vnd.cncf.helm.chart.content.v1.tar+gzip'
  verify:
    provider: cosign
    matchOIDCIdentity:
      - issuer: '^https://token.actions.githubusercontent.com$'
        subject: '^https://github.com/home-operations/tuppr.*$'
