---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: velero
  namespace: velero
spec:
  chart:
    spec:
      chart: velero
      version: '5.1.5'
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: vmware-tanzu
        namespace: flux-system
  install:
    createNamespace: true
    crds: Skip
  upgrade:
    crds: Skip
  values:
    image:
      repository: velero/velero
      tag: v1.12.2 # downgrade due to missing CRDs in helm chart
    initContainers:
      - name: velero-plugin-for-aws
        image: velero/velero-plugin-for-aws:latest
        volumeMounts:
          - mountPath: /target
            name: plugins
    upgradeCRDs: false
    configuration:
      backupStorageLocation:
        - name: default
          provider: aws
          bucket: velero-infrastructure
          config:
            region: minio
            s3Url: http://${IP_RYLOTH_TAILSCALE}:9000
            s3ForcePathStyle: true
      uploaderType: restic
      logLevel: warning
      extraEnvVars:
        TZ: ${TIMEZONE}
      defaultVolumesToFsBackup: true
    credentials:
      secretContents:
        cloud: |
          [default]
          aws_access_key_id=${VELERO_ACCESS_KEY}
          aws_secret_access_key=${VELERO_SECRET_KEY}
    backupsEnabled: true
    snapshotsEnabled: false
    deployNodeAgent: true
    nodeAgent:
      tolerations:
        - key: k8s.pascaliske.dev/location
          operator: Equal
          value: public
          effect: NoSchedule
    schedules:
      weekly:
        schedule: '0 3 * * 0' # every sunday at 3am
        template:
          includedNamespaces:
            - '*'
  interval: 10m0s
