---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: redis-operator-source
  namespace: flux-system
spec:
  url: https://github.com/freshworks/redis-operator
  ref:
    # renovate: datasource=github-releases depName=freshworks/redis-operator
    tag: Chart-3.2.9
  interval: 15m
  ignore: |
    # exclude all
    /*
    # include crds directory
    !/charts/redisoperator/crds
