---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cloudnative-pg-crds
  namespace: flux-system
spec:
  sourceRef:
    kind: GitRepository
    name: cloudnative-pg-source
  interval: 15m
  prune: false
  healthChecks:
    - apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      name: backups.postgresql.cnpg.io
    - apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      name: clusterimagecatalogs.postgresql.cnpg.io
    - apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      name: clusters.postgresql.cnpg.io
    - apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      name: databases.postgresql.cnpg.io
    - apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      name: imagecatalogs.postgresql.cnpg.io
    - apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      name: poolers.postgresql.cnpg.io
    - apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      name: publications.postgresql.cnpg.io
    - apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      name: scheduledbackups.postgresql.cnpg.io
    - apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      name: subscriptions.postgresql.cnpg.io
