---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: clickhouse-operator
  namespace: clickhouse-operator-system
spec:
  chartRef:
    kind: OCIRepository
    name: clickhouse-operator
    namespace: flux-system
  values: # defaults: https://github.com/ClickHouse/clickhouse-operator/blob/main/dist/chart/values.yaml
    crd:
      enable: false
    prometheus:
      enable: true
  interval: 10m0s
