---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: authelia
resources:
  - secrets.sops.yaml
  - oidc-jwks-key.sops.yaml
configMapGenerator:
  - name: authelia-users
    files:
      - users.yaml
generatorOptions:
  disableNameSuffixHash: true
