---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: paperless
  namespace: paperless
spec:
  chart:
    spec:
      chart: paperless
      version: '7.0.0'
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: pascaliske
        namespace: flux-system
  values:
    image:
      registry: ghcr.io
      repository: paperless-ngx/paperless-ngx
      tag: '2.20.5'
    ingressRoute:
      create: true
      entryPoints:
        - https
      rule: Host(`docs.${DOMAIN_EXTERNAL}`)
      middlewares:
        - name: auth
          namespace: traefik
        - name: security
          namespace: traefik
        - name: optimizations
          namespace: traefik
        - name: error-pages
          namespace: traefik-errors
    certificate:
      create: true
      dnsNames:
        - docs.${DOMAIN_EXTERNAL}
      issuerRef:
        kind: ClusterIssuer
        name: lets-encrypt-production
    env:
      - name: TZ
        value: ${TIMEZONE}
      - name: PAPERLESS_URL
        value: https://docs.${DOMAIN_EXTERNAL}
      - name: PAPERLESS_DBENGINE
        value: postgresql
      - name: PAPERLESS_DBHOST
        value: postgresql-rw
      - name: PAPERLESS_DBPORT
        value: '5432'
      - name: PAPERLESS_DBNAME
        value: paperless
      - name: PAPERLESS_DBUSER
        valueFrom:
          secretKeyRef:
            name: postgresql-user
            key: username
      - name: PAPERLESS_DBPASS
        valueFrom:
          secretKeyRef:
            name: postgresql-user
            key: password
      - name: PAPERLESS_ADMIN_USER
        value: ${PAPERLESS_ADMIN_USER}
      - name: PAPERLESS_ADMIN_PASSWORD
        value: ${PAPERLESS_ADMIN_PASSWORD}
      - name: PAPERLESS_ADMIN_MAIL
        value: ${PAPERLESS_ADMIN_EMAIL}
      - name: PAPERLESS_ENABLE_HTTP_REMOTE_USER
        value: 'true'
      - name: PAPERLESS_LOGOUT_REDIRECT_URL
        value: https://auth.${DOMAIN_EXTERNAL}/logout?rd=https://docs.${DOMAIN_EXTERNAL}
      - name: PAPERLESS_ALLOWED_HOSTS
        value: '*'
      - name: PAPERLESS_OCR_LANGUAGE
        value: deu
      - name: PAPERLESS_IGNORE_DATES
        value: ${PAPERLESS_IGNORE_DATES}
      - name: PAPERLESS_ENABLE_UPDATE_CHECK
        value: 'true'
      - name: PAPERLESS_ENABLE_COMPRESSION
        value: 'false'
    secret:
      create: true
      values:
        PAPERLESS_SECRET_KEY: ${PAPERLESS_SECRET_KEY}
    persistentVolumeClaim:
      size: 10Gi
      storageClassName: local-path
    export:
      enabled: true
    trash:
      enabled: true
    redis:
      enabled: true
      fullnameOverride: redis
  interval: 10m0s
