# yaml-language-server: $schema=https://json.schemastore.org/yamllint.json
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgresql
  namespace: authelia
spec:
  instances: 3
  imageName: ghcr.io/cloudnative-pg/postgresql:18.2
  primaryUpdateStrategy: unsupervised
  storage:
    storageClass: local-path
    size: 1Gi
  superuserSecret:
    name: postgresql-superuser
  bootstrap:
    initdb:
      database: authelia
      owner: authelia
      secret:
        name: postgresql-user
  monitoring:
    enablePodMonitor: true
