---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cloudnative-pg
  namespace: cloudnative-pg
spec:
  chart:
    spec:
      chart: cloudnative-pg
      version: '0.26.0'
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: cloudnative-pg
        namespace: flux-system
  values:
    image:
      repository: ghcr.io/cloudnative-pg/cloudnative-pg
      tag: '1.27.0'
  interval: 10m0s
