ports:
  dns: 53
  http: 4000

log:
  level: info
  format: text

upstream:
  default:
    - unbound-dns.unbound.svc.cluster.local:5053
    - cloudflared-dns.cloudflared.svc.cluster.local:5053

customDNS:
  mapping:
    # general
    iske.cloud: ${IP_CORUSCANT}

    # servers
    corsucant.iske.cloud: ${IP_CORUSCANT}
    alderaan.iske.cloud: ${IP_ALDERAAN}
    dathomir.iske.cloud: ${IP_DATHOMIR}
    mustafar.iske.cloud: ${IP_MUSTAFAR}
    jakku.iske.cloud: ${IP_JAKKU}
    ryloth.iske.cloud: ${IP_RYLOTH}
    ilum.iske.cloud: ${IP_ILUM}

    # misc
    unifi: ${IP_CORUSCANT} # simplifies unifi layer 2 device adoption

conditional:
  mapping:
    fritz.box: ${IP_ROUTER}

clientLookup:
  upstream: ${IP_ROUTER}
  singleNameOrder:
    - 2
    - 1

blocking:
  blackLists:
    all:
      - https://blocklistproject.github.io/Lists/ads.txt
      - https://blocklistproject.github.io/Lists/drugs.txt
      - https://blocklistproject.github.io/Lists/fraud.txt
      - https://blocklistproject.github.io/Lists/malware.txt
      - https://blocklistproject.github.io/Lists/phishing.txt
      - https://blocklistproject.github.io/Lists/porn.txt
      - https://blocklistproject.github.io/Lists/scam.txt
      - https://blocklistproject.github.io/Lists/tiktok.txt
      - https://raw.githubusercontent.com/anudeepND/blacklist/master/adservers.txt
      - https://raw.githubusercontent.com/matomo-org/referrer-spam-blacklist/master/spammers.txt
      - https://raw.githubusercontent.com/pascaliske/infrastructure/master/cluster/services/blocky/blocklist.txt
  whiteLists:
    all:
      - https://raw.githubusercontent.com/pascaliske/infrastructure/master/cluster/services/blocky/allowlist.txt
  clientGroupsBlock:
    default:
      - all
  startStrategy: fast

caching:
  minTime: 5m
  maxTime: 20m
  prefetching: true

redis:
  address: redis.redis.svc.cluster.local:6379

prometheus:
  enable: true

queryLog:
  type: none
