---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: blocky
  namespace: blocky
spec:
  chart:
    spec:
      chart: blocky
      version: '10.5.2'
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
  values:
    image:
      repository: ghcr.io/0xerr0r/blocky
      tag: v0.26.2
    controller:
      type: daemonset
      strategy: RollingUpdate
      rollingUpdate:
        surge: 1
        unavailable: 0
    env:
      TZ: ${TIMEZONE}
    service:
      main:
        enabled: true
      dns-tcp:
        enabled: true
        type: LoadBalancer
      dns-udp:
        enabled: true
        type: LoadBalancer
    persistence:
      logs:
        enabled: false
        mountPath: /logs
        accessMode: ReadWriteOnce
        size: 512Mi
    metrics:
      enabled: true
      prometheusRule:
        enabled: true
    tolerations:
      - key: node-role.kubernetes.io/control-plane
        operator: Exists
        effect: NoSchedule
      - key: k8s.pascaliske.dev/location
        operator: Equal
        value: public
        effect: NoSchedule
  valuesFrom:
    - kind: ConfigMap
      name: blocky-config
      valuesKey: config.yml
      targetPath: config
  interval: 10m0s
