---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: blocky
resources:
  - namespace.yaml
  - redis.yaml
  - helm-release.yaml
  - certificate.yaml
  - route.yaml
  - dashboard
configMapGenerator:
  - name: blocky-config
    files:
      - config.yml
configurations:
  - kustomizeconfig.yaml
