---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: velero-source
  namespace: flux-system
spec:
  url: https://github.com/vmware-tanzu/helm-charts
  ref:
    # renovate: registryUrl=https://vmware-tanzu.github.io/helm-charts chart=velero
    tag: velero-3.1.6
  interval: 15m
  ignore: |
    # exclude all
    /*
    # include crds directory
    !/charts/velero/crds
