{
 "title": "MagicMirror",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Version",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "magicmirror_build_info" }
   ]
  },
  {
   "title": "Socket Clients",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "magicmirror_socket_clients" }
   ]
  },
  {
   "title": "Config Reloads",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "magicmirror_config_reloads_total"
    }
   ]
  },
  {
   "title": "Config Reload Failure",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "magicmirror_config_last_reload_failure <= 0 or time() - magicmirror_config_last_reload_failure"
    }
   ]
  },
  {
   "title": "Config Reload Success",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 13, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "magicmirror_config_last_reload_success <= 0 or time() - magicmirror_config_last_reload_success"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 5, "w": 7, "x": 17, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "magicmirror_uptime_seconds" }
   ]
  },
  { "title": "HTTP", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Requests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "sum(rate(magicmirror_requests_total[5m])) by (method)",
     "legendFormat": "{{ method }}"
    }
   ]
  },
  {
   "title": "Average request duration",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(magicmirror_request_duration_seconds_sum[5m])) by (instance) / sum(rate(magicmirror_request_duration_seconds_count[5m])) by (instance)"
    }
   ]
  }
 ]
}