---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cloudflare-exporter
  namespace: monitoring
spec:
  chart:
    spec:
      chart: cloudflare-exporter
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: cloudflare-exporter
        namespace: flux-system
  install:
    createNamespace: true
  values:
    image:
      repository: ghcr.io/lablabs/cloudflare_exporter
      tag: 0.0.14
    env:
      - name: TZ
        value: ${TIMEZONE}
      - name: CF_API_TOKEN
        value: ${CLOUDFLARE_API_TOKEN_METRICS}
      - name: CF_ZONES
        value: ${CLOUDFLARE_ZONES}
      - name: FREE_TIER
        value: 'true'
    serviceMonitor:
      enabled: true
    tolerations:
      - key: k8s.pascaliske.dev/location
        operator: Equal
        value: public
        effect: NoSchedule
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: k8s.pascaliske.dev/location
                  operator: In
                  values:
                    - public
  interval: 10m0s
