- name: Configure journald
  become: true
  block:
    - name: Set SystemMaxUse for journald
      lineinfile:
        path: /etc/systemd/journald.conf
        line: 'SystemMaxUse={{ journal_size }}'
        regexp: '^#?SystemMaxUse'
      register: system_max_use
    - name: Set MaxFileSec for journald
      lineinfile:
        path: /etc/systemd/journald.conf
        line: 'MaxFileSec={{ journal_retention }}'
        regexp: '^#?MaxFileSec'
      register: max_file_sec
    - name: Restart journald
      systemd:
        name: systemd-journald
        state: restarted
      when: system_max_use.changed or max_file_sec.changed
