---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: linkding
  namespace: linkding
spec:
  chart:
    spec:
      chart: linkding
      version: '2.0.0'
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: pascaliske
        namespace: flux-system
  values:
    image:
      repository: sissbruecker/linkding
      tag: 1.40.0
    ingressRoute:
      create: true
      entryPoints:
        - https
      rule: Host(`links.${DOMAIN_EXTERNAL}`)
      middlewares:
        - name: auth
          namespace: traefik
        - name: security
          namespace: traefik
        - name: optimizations
          namespace: traefik
        - name: error-pages
          namespace: traefik-errors
    certificate:
      create: true
      dnsNames:
        - links.${DOMAIN_EXTERNAL}
      issuerRef:
        kind: ClusterIssuer
        name: lets-encrypt-production
    env:
      - name: TZ
        value: ${TIMEZONE}
      - name: LD_SUPERUSER_NAME
        value: ${LINKDING_ADMIN_USER}
      - name: LD_SUPERUSER_PASSWORD
        value: ${LINKDING_ADMIN_PASSWORD}
      - name: LD_ENABLE_AUTH_PROXY
        value: 'True'
      - name: LD_AUTH_PROXY_USERNAME_HEADER
        value: HTTP_REMOTE_USER
      - name: LD_AUTH_PROXY_LOGOUT_URL
        value: https://auth.${DOMAIN_EXTERNAL}/logout?rd=https://links.${DOMAIN_EXTERNAL}
      - name: LD_DB_ENGINE
        value: postgres
      - name: LD_DB_HOST
        value: postgresql-rw
      - name: LD_DB_PORT
        value: '5432'
      - name: LD_DB_DATABASE
        value: linkding
      - name: LD_DB_USER
        valueFrom:
          secretKeyRef:
            name: postgresql-user
            key: username
      - name: LD_DB_PASSWORD
        valueFrom:
          secretKeyRef:
            name: postgresql-user
            key: password
      - name: LD_LOG_X_FORWARDED_FOR
        value: 'true'
      - name: LD_DISABLE_REQUEST_LOGS
        value: 'true'
    persistentVolumeClaim:
      create: false
  interval: 10m0s
