---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: trivy-operator
  namespace: trivy-system
spec:
  chart:
    spec:
      chart: trivy-operator
      version: '0.31.0'
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: aquasecurity
        namespace: flux-system
  install:
    crds: Skip
  upgrade:
    crds: Skip
  values:
    excludeNamespaces: "{{ .Release.Namespace }}"
    operator:
      scanJobsConcurrentLimit: 3
      vulnerabilityScannerScanOnlyCurrentRevisions: true
      configAuditScannerScanOnlyCurrentRevisions: true
    serviceMonitor:
      enabled: true
    trivy:
      ignoreUnfixed: true
  interval: 10m0s
