---
# common
common_static_ip: "{{ vault.ips[hostname_prefix] }}"
common_static_router: '{{ vault.ips.router }}'
common_static_dns: '{{ vault.ips.router }}'

# tailscale
tailscale_auth_key: '{{ vault.tailscale.auth_key }}'

# k3s
k3s_url: '{{ vault.ips.tailscale_coruscant }}'
k3s_token: '{{ vault.k3s.registration_token }}'
k3s_advertise_address: "{{ vault.ips['tailscale_' ~ hostname_prefix] }}"
k3s_node_ip: "{{ vault.ips['tailscale_' ~ hostname_prefix] }}"
k3s_node_ip_external: "{{ vault.ips[hostname_prefix] }}"
k3s_node_interface: tailscale0
k3s_kubeconfig_local: "{{ lookup('env', 'HOME') }}/.kube/infrastructure/config"
