---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: snapdrop
  namespace: snapdrop
spec:
  chart:
    spec:
      chart: snapdrop
      version: '2.0.0'
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: pascaliske
        namespace: flux-system
  install:
    createNamespace: true
  values:
    image:
      repository: ghcr.io/linuxserver/snapdrop
      tag: latest
    ingressRoute:
      create: true
      entryPoints:
        - https
      rule: Host(`drop.${DOMAIN_INTERNAL}`)
      middlewares:
        - name: security
          namespace: traefik
        - name: optimizations
          namespace: traefik
        - name: error-pages
          namespace: traefik-errors
    certificate:
      create: true
      dnsNames:
        - drop.${DOMAIN_INTERNAL}
      issuerRef:
        kind: ClusterIssuer
        name: lets-encrypt-production
    env:
      - name: TZ
        value: ${TIMEZONE}
      - name: PGID
        value: '${GID}'
      - name: PUID
        value: '${UID}'
    resources:
      limits:
        cpu: 100m
        memory: 128Mi
      requests:
        cpu: 100m
        memory: 128Mi
  interval: 10m0s
