# yaml-language-server: $schema=https://json.schemastore.org/yamllint.json
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgresql
  namespace: linkding
spec:
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:15.13
  primaryUpdateStrategy: unsupervised
  storage:
    size: 1Gi
  superuserSecret:
    name: postgresql-superuser
  bootstrap:
    initdb:
      database: linkding
      owner: linkding
      secret:
        name: postgresql-user
  monitoring:
    enablePodMonitor: true
