# directories
- name: Ensure directories exist
  file:
    path: '{{ root_path }}/{{ item }}'
    state: directory
  loop:
    - '{{ role_name }}'

# glances
- name: Create configuration file
  template:
    src: '{{ role_name }}/glances.conf.j2'
    dest: '{{ root_path }}/{{ role_name }}/glances.conf'
