version: '3.7'
services:
  # maintenance
  watchtower:
    image: containrrr/watchtower:latest
    container_name: watchtower
    restart: always
    environment:
      TZ: '{{ timezone }}'
      DOCKER_HOST: tcp://docker-proxy:2375
      WATCHTOWER_SCHEDULE: '{{ watchtower_schedule | default("0 0 0 * * *") }}'
      WATCHTOWER_NOTIFICATIONS: shoutrrr
      WATCHTOWER_NOTIFICATIONS_LEVEL: '{{ watchtower_slack_level }}'
      WATCHTOWER_NOTIFICATION_URL: '{{ watchtower_slack_url }}'
      WATCHTOWER_NOTIFICATION_TEMPLATE: '{{ watchtower_slack_template }}'
      WATCHTOWER_CLEANUP: '{{ watchtower_cleanup | default(true) }}'
      WATCHTOWER_DEBUG: '{{ watchtower_debug | default(false) }}'
    networks:
      - docker
  dozzle:
    image: amir20/dozzle:latest
    container_name: dozzle
    restart: always
    expose:
      - 8080
    environment:
      DOCKER_HOST: tcp://docker-proxy:2375
    networks:
      - proxy
      - docker
    labels:
      - traefik.enable=true
      - traefik.http.routers.dozzle.rule=Host(`logs.{{ domain }}`)
      - traefik.http.routers.dozzle.entrypoints=https
      - traefik.http.routers.dozzle.tls=true
      - traefik.http.routers.dozzle.tls.certresolver=http
      - traefik.http.routers.dozzle.middlewares=auth@file,rate-limit@file
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: unless-stopped
    command: --host tcp://docker-proxy:2375
    expose:
      - 9000
    volumes:
      - portainer:/data
    networks:
      - proxy
      - docker
    labels:
      - traefik.enable=true
      - traefik.http.routers.portainer.rule=Host(`portainer.{{ domain }}`)
      - traefik.http.routers.portainer.entrypoints=https
      - traefik.http.routers.portainer.tls=true
      - traefik.http.routers.portainer.tls.certresolver=http
      - traefik.http.routers.portainer.middlewares=auth@file,rate-limit@file
      - traefik.http.services.portainer-gitlab.loadbalancer.server.port=9000
  glances:
    image: nicolargo/glances:latest
    container_name: glances
    restart: unless-stopped
    environment:
      TZ: '{{ timezone }}'
      DOCKER_HOST: tcp://docker-proxy:2375
      GLANCES_OPT: '-w'
    expose:
      - 61208
    volumes:
      - /:/rootfs:ro
      - '{{ root_path }}/glances/glances.conf:/glances/conf/glances.conf'
    networks:
      - proxy
      - docker
    labels:
      - traefik.enable=true
      - traefik.http.routers.glances.rule=Host(`stats.{{ domain }}`)
      - traefik.http.routers.glances.entrypoints=https
      - traefik.http.routers.glances.tls=true
      - traefik.http.routers.glances.tls.certresolver=http
      - traefik.http.routers.glances.middlewares=auth@file,rate-limit@file
      - traefik.http.services.glances-gitlab.loadbalancer.server.port=61208

  # security
  docker-proxy:
    image: tecnativa/docker-socket-proxy:latest
    container_name: docker-proxy
    restart: always
    expose:
      - 2375
    environment:
      INFO: 1
      CONTAINERS: 1
      IMAGES: 1
      NETWORKS: 1
      VOLUMES: 1
      SERVICES: 1
      POST: 1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - docker
  fail2ban:
    image: crazymax/fail2ban:latest
    container_name: fail2ban
    restart: always
    network_mode: host
    environment:
      TZ: '{{ timezone }}'
      F2B_LOG_TARGET: STDOUT
      F2B_LOG_LEVEL: INFO
      F2B_DB_PURGE_AGE: 1d
      SSMTP_HOST: '{{ mail.host }}'
      SSMTP_PORT: '{{ mail.port }}'
      # SSMTP_HOSTNAME: example.com
      SSMTP_USER: '{{ mail.accounts.auth.email }}'
      SSMTP_PASSWORD: '{{ mail.accounts.auth.password }}'
      SSMTP_TLS: 'YES'
    volumes:
      - /var/log:/var/log:ro
      - '{{ root_path }}/fail2ban:/data'
    cap_add:
      - NET_ADMIN
      - NET_RAW

  # proxy
  traefik:
    image: traefik:latest
    container_name: traefik
    restart: unless-stopped
    healthcheck:
      test: traefik healthcheck
      interval: 30s
      timeout: 3s
      retries: 30
    ports:
      - '80:80'
      - '443:443'
    environment:
      TZ: '{{ timezone }}'
      DO_AUTH_TOKEN: '{{ digital_ocean_token }}'
    volumes:
      - /var/log/traefik:/var/log
      - '{{ root_path }}/traefik.yml:/etc/traefik/traefik.yml'
      - '{{ root_path }}/traefik:/etc/traefik'
    networks:
      - proxy
      - docker
    labels:
      - traefik.enable=true
      - traefik.http.routers.api.rule=Host(`traefik.{{ domain }}`)
      - traefik.http.routers.api.entrypoints=https
      - traefik.http.routers.api.service=api@internal
      - traefik.http.routers.api.tls=true
      - traefik.http.routers.api.tls.certresolver=http
      - traefik.http.routers.api.middlewares=auth@file,rate-limit@file
  authelia:
    image: authelia/authelia
    container_name: authelia
    restart: unless-stopped
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:9091 || exit 1
      interval: 30s
      timeout: 3s
      retries: 30
    expose:
      - 9091
    environment:
      TZ: '{{ timezone }}'
      PUID: 0
      PGID: 0
    volumes:
      - /var/log/authelia:/var/log
      - '{{ root_path }}/authelia:/config'
    networks:
      - proxy
    labels:
      - traefik.enable=true
      - traefik.http.routers.authelia.rule=Host(`auth.{{ domain }}`)
      - traefik.http.routers.authelia.entrypoints=https
      - traefik.http.routers.authelia.tls=true
      - traefik.http.routers.authelia.tls.certresolver=http
      - traefik.http.routers.authelia.middlewares=rate-limit@file,authelia-headers
      - traefik.http.middlewares.authelia-headers.headers.browserXssFilter=true
      - traefik.http.middlewares.authelia-headers.headers.customResponseHeaders.Cache-Control=no-store
      - traefik.http.middlewares.authelia-headers.headers.customResponseHeaders.Pragma=no-cache
      - traefik.http.middlewares.authelia-headers.headers.customFrameOptionsValue=SAMEORIGIN

  # services
  homer:
    image: b4bz/homer:latest
    container_name: homer
    restart: always
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8080 || exit 1
      interval: 30s
      timeout: 3s
      retries: 30
    expose:
      - 8080
    environment:
      TZ: '{{ timezone }}'
      UID: 0
      GID: 0
    volumes:
      - '{{ root_path }}/homer/assets:/www/assets'
      - '{{ root_path }}/homer/config.yml:/www/assets/config.yml'
    networks:
      - proxy
    labels:
      - traefik.enable=true
      - traefik.http.routers.homer.rule=Host(`go.{{ domain }}`)
      - traefik.http.routers.homer.entrypoints=https
      - traefik.http.routers.homer.tls=true
      - traefik.http.routers.homer.tls.certresolver=http
      - traefik.http.routers.homer.middlewares=rate-limit@file
  gitlab:
    image: gitlab/gitlab-ce:latest
    container_name: gitlab
    restart: unless-stopped
    hostname: git.{{ domain }}
    environment:
      TZ: '{{ timezone }}'
    ports:
      - '2222:22'
    volumes:
      - '{{ root_path }}/gitlab/config:/etc/gitlab'
      - '{{ root_path }}/gitlab/data:/var/opt/gitlab'
      - '{{ root_path }}/gitlab/backups:/var/opt/gitlab-backups'
      - '{{ root_path }}/gitlab/logs:/var/log/gitlab'
    networks:
      - proxy
    labels:
      - traefik.enable=true
      - traefik.http.routers.gitlab.rule=Host(`git.{{ domain }}`)
      - traefik.http.routers.gitlab.entrypoints=https
      - traefik.http.routers.gitlab.service=gitlab-gitlab
      - traefik.http.routers.gitlab.tls=true
      - traefik.http.routers.gitlab.tls.certresolver=http
      - traefik.http.routers.gitlab.middlewares=rate-limit@file
      - traefik.http.services.gitlab-gitlab.loadbalancer.server.port=80
      - traefik.http.routers.registry.rule=Host(`registry.{{ domain }}`)
      - traefik.http.routers.registry.entrypoints=https
      - traefik.http.routers.registry.service=gitlab-registry
      - traefik.http.routers.registry.tls=true
      - traefik.http.routers.registry.tls.certresolver=http
      - traefik.http.routers.registry.middlewares=rate-limit@file
      - traefik.http.services.gitlab-registry.loadbalancer.server.port=80
  gitlab-runner:
    image: gitlab/gitlab-runner:alpine
    container_name: gitlab-runner
    restart: unless-stopped
    environment:
      DOCKER_HOST: tcp://docker-proxy:2375
    volumes:
      - '{{ root_path }}/gitlab-runner:/etc/gitlab-runner'
    networks:
      - docker
  code-server:
    image: codercom/code-server
    container_name: code-server
    restart: unless-stopped
    user: '${HOST_UID}:${HOST_GID}'
    working_dir: /home/coder/projects
    environment:
      TZ: '{{ timezone }}'
      XDG_DATA_HOME: /home/coder
      XDG_CONFIG_HOME: /home/coder/.config
      PROXY_DOMAIN: 'code.{{ domain }}'
    volumes:
      - '{{ root_path }}/code-server/data:/home/coder/code-server'
      - '{{ root_path }}/code-server/config.yml:/home/coder/.config/code-server/config.yaml'
      - '{{ root_path }}/projects:/home/coder/projects'
    networks:
      - proxy
    labels:
      - traefik.enable=true
      - traefik.http.routers.code-server.rule=Host(`code.{{ domain }}`)
      - traefik.http.routers.code-server.entrypoints=https
      - traefik.http.routers.code-server.tls=true
      - traefik.http.routers.code-server.tls.certresolver=http
      - traefik.http.routers.code-server.middlewares=auth@file,rate-limit@file
  linkding:
    image: sissbruecker/linkding:latest
    container_name: linkding
    restart: unless-stopped
    environment:
      TZ: '{{ timezone }}'
    volumes:
      - '{{ root_path }}/linkding:/etc/linkding/data'
    networks:
      - proxy
    labels:
      - traefik.enable=true
      - traefik.http.routers.linkding.rule=Host(`links.{{ domain }}`)
      - traefik.http.routers.linkding.entrypoints=https
      - traefik.http.routers.linkding.tls=true
      - traefik.http.routers.linkding.tls.certresolver=http
      - traefik.http.routers.linkding.middlewares=auth@file,rate-limit@file
      - traefik.http.services.linkding-gitlab.loadbalancer.server.port=9090
  paperless:
    image: jonaswinkler/paperless-ng:latest
    container_name: paperless
    restart: unless-stopped
    depends_on:
      - redis
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
      interval: 30s
      timeout: 10s
      retries: 5
    environment:
      TZ: '{{ timezone }}'
      PAPERLESS_REDIS: redis://redis:6379
      PAPERLESS_TIME_ZONE: '{{ timezone }}'
      PAPERLESS_SECRET_KEY: '{{ paperless_secret_key }}'
      PAPERLESS_ENABLE_HTTP_REMOTE_USER: 'true'
      PAPERLESS_OCR_LANGUAGE: 'deu'
    volumes:
      - paperless:/usr/src/paperless
      - '{{ root_path }}/paperless/export:/usr/src/paperless/export'
      - '{{ root_path }}/paperless/import:/usr/src/paperless/consume'
    networks:
      - proxy
      - redis
    labels:
      - traefik.enable=true
      - traefik.http.routers.paperless.rule=Host(`docs.{{ domain }}`)
      - traefik.http.routers.paperless.entrypoints=https
      - traefik.http.routers.paperless.tls=true
      - traefik.http.routers.paperless.tls.certresolver=http
      - traefik.http.routers.paperless.middlewares=auth@file,rate-limit@file
      - traefik.http.services.paperless-gitlab.loadbalancer.server.port=8000

  # dependencies
  redis:
    image: redis:latest
    container_name: redis
    restart: unless-stopped
    expose:
      - 6379
    networks:
      - redis
networks:
  proxy:
    ipam:
      config:
        - subnet: 172.20.1.0/24
          gateway: 172.20.1.1
  docker:
    ipam:
      config:
        - subnet: 172.20.2.0/24
          gateway: 172.20.2.1
  redis:
    ipam:
      config:
        - subnet: 172.20.3.0/24
          gateway: 172.20.3.1
volumes:
  portainer:
  paperless:
