{
 "title": "Climate",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Temperature",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "expr": "label_replace(homeassistant_temperature_c, \"short_name\", \"$1\", \"friendly_name\", \"(.*) Climate temperature\")",
     "legendFormat": "{{ short_name }}"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "label_replace(homeassistant_humidity_percent, \"short_name\", \"$1\", \"friendly_name\", \"(.*) Climate humidity\")",
     "legendFormat": "{{ short_name }}"
    }
   ]
  },
  {
   "title": "Pressure",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "pressurehpa" } },
   "yaxes": [
    { "format": "pressurehpa" }
   ],
   "targets": [
    {
     "expr": "label_replace(homeassistant_pressure_hpa, \"short_name\", \"$1\", \"friendly_name\", \"(.*) Climate pressure\")",
     "legendFormat": "{{ short_name }}"
    }
   ]
  }
 ]
}