---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: plausible
  namespace: plausible
spec:
  chart:
    spec:
      chart: plausible
      version: '0.1.4'
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: pascaliske
        namespace: flux-system
  install:
    createNamespace: true
  values:
    image:
      repository: plausible/analytics
      tag: v1.5.1
    ingressRoute:
      create: true
      entryPoints:
        - https
      rule: Host(`analytics.${DOMAIN_EXTERNAL}`)
      middlewares:
        - name: auth-external
          namespace: traefik
        - name: security
          namespace: traefik
        - name: optimizations
          namespace: traefik
        - name: error-pages
          namespace: traefik-errors
    certificate:
      create: true
      dnsNames:
        - analytics.${DOMAIN_EXTERNAL}
      issuerRef:
        kind: ClusterIssuer
        name: lets-encrypt-production
    env:
      - name: TZ
        value: ${TIMEZONE}
      - name: BASE_URL
        value: https://analytics.${DOMAIN_EXTERNAL}
      - name: SECRET_KEY_BASE
        valueFrom:
          secretKeyRef:
            name: plausible-secrets
            key: SECRET_KEY_BASE
      - name: DATABASE_URL
        valueFrom:
          secretKeyRef:
            name: plausible-secrets
            key: DATABASE_URL
      - name: CLICKHOUSE_DATABASE_URL
        valueFrom:
          secretKeyRef:
            name: plausible-secrets
            key: CLICKHOUSE_DATABASE_URL
      - name: MAILER_EMAIL
        value: '${SMTP_ACCOUNT_PLAUSIBLE_EMAIL}'
      - name: SMTP_HOST_ADDR
        value: '${SMTP_HOST}'
      - name: SMTP_HOST_PORT
        value: '465'
      - name: SMTP_USER_NAME
        value: '${SMTP_ACCOUNT_PLAUSIBLE_EMAIL}'
      - name: SMTP_USER_PWD
        value: '${SMTP_ACCOUNT_PLAUSIBLE_PASSWORD}'
      - name: SMTP_HOST_SSL_ENABLED
        value: 'true'
      - name: DISABLE_REGISTRATION
        value: 'true'
      - name: GOOGLE_CLIENT_ID
        valueFrom:
          secretKeyRef:
            name: plausible-secrets
            key: GOOGLE_CLIENT_ID
      - name: GOOGLE_CLIENT_SECRET
        valueFrom:
          secretKeyRef:
            name: plausible-secrets
            key: GOOGLE_CLIENT_SECRET
    geoip:
      enabled: true
      image:
        repository: ghcr.io/maxmind/geoipupdate
        tag: v5.1.0
      accountId: '${PLAUSIBLE_GEOIP_ACCOUNT_ID}'
      licenseKey: ${PLAUSIBLE_GEOIP_LICENSE_KEY}
    tolerations:
      - key: k8s.pascaliske.dev/location
        operator: Equal
        value: public
        effect: NoSchedule
  interval: 10m0s
