---
apiVersion: upgrade.cattle.io/v1
kind: Plan
metadata:
  name: master
  namespace: system-upgrade
spec:
  # renovate: datasource=github-releases depName=k3s-io/k3s (1)
  version: "v1.29.4+k3s1"
  serviceAccountName: system-upgrade
  concurrency: 1
  cordon: true
  nodeSelector:
    matchExpressions:
      # only control-plane nodes (2)
      - key: node-role.kubernetes.io/control-plane
        operator: Exists
  tolerations:
    - key: node-role.kubernetes.io/control-plane
      operator: Exists
      effect: NoSchedule
  upgrade:
    image: rancher/k3s-upgrade
