---
apiVersion: upgrade.cattle.io/v1
kind: Plan
metadata:
  name: worker
  namespace: system-upgrade
spec:
  # renovate: datasource=github-releases depName=k3s-io/k3s
  version: "v1.30.1+k3s1"
  serviceAccountName: system-upgrade
  concurrency: 1
  nodeSelector:
    # only worker nodes
    matchExpressions:
      - key: node-role.kubernetes.io/control-plane
        operator: DoesNotExist
  tolerations:
    - key: k8s.pascaliske.dev/location
      operator: Equal
      value: public
      effect: NoSchedule
  prepare:
    image: rancher/k3s-upgrade
    args: ["prepare", "master"]
  upgrade:
    image: rancher/k3s-upgrade
