# yaml-language-server: $schema=https://json.schemastore.org/yamllint.json
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgresql
  namespace: plausible
spec:
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:17.6
  primaryUpdateStrategy: unsupervised
  storage:
    size: 1Gi
  superuserSecret:
    name: postgresql-superuser
  bootstrap:
    initdb:
      database: plausible
      owner: plausible
      secret:
        name: postgresql-user
  monitoring:
    enablePodMonitor: true
