---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: shlink.${DOMAIN_INTERNAL}
  namespace: shlink
spec:
  secretName: shlink.${DOMAIN_INTERNAL}
  dnsNames:
    - shlink.${DOMAIN_INTERNAL}
  issuerRef:
    kind: ClusterIssuer
    name: lets-encrypt-production
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: go.${DOMAIN_EXTERNAL}
  namespace: shlink
spec:
  secretName: go.${DOMAIN_EXTERNAL}
  dnsNames:
    - go.${DOMAIN_EXTERNAL}
  issuerRef:
    kind: ClusterIssuer
    name: lets-encrypt-production
