---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: redis-operator
  namespace: redis-operator
spec:
  chart:
    spec:
      chart: redis-operator
      version: '3.3.4'
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: redis-operator
        namespace: flux-system
  install:
    crds: Skip
  upgrade:
    crds: Skip
  values:
    image:
      repository: ghcr.io/freshworks-oss/redis-operator
      tag: v3.3.5
    monitoring:
      enabled: true
      serviceMonitor: true
  postRenderers:
    - kustomize:
        patches:
          - target:
              kind: Deployment
              name: redis-operator
            patch: |
              apiVersion: apps/v1
              kind: Deployment
              metadata:
                name: redis-operator
              spec:
                template:
                  spec:
                    containers:
                      - name: redis-operator
                        env:
                          - name: OPERATOR_GROUP_ID
                            value: main
  interval: 10m0s
