---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: node-problem-detector
  namespace: kube-system
spec:
  chartRef:
    kind: OCIRepository
    name: node-problem-detector
    namespace: flux-system
  values: # defaults: https://github.com/deliveryhero/helm-charts/blob/master/stable/node-problem-detector/values.yaml
    image:
      repository: registry.k8s.io/node-problem-detector/node-problem-detector
      tag: v1.36.0
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
      prometheusRule:
        enabled: true
  interval: 10m0s
