---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: clickhouse
  namespace: clickhouse
spec:
  chart:
    spec:
      chart: clickhouse
      version: '0.3.1'
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: pascaliske
        namespace: flux-system
  values:
    image:
      repository: clickhouse/clickhouse-server
      tag: 24.12.6.70-alpine
    env:
      - name: TZ
        value: ${TIMEZONE}
    configMap:
      files:
        # temporary fix for plausible <-> clickhouse 24.2 support
        # https://togithub.com/plausible/analytics/issues/3855
        clickhouse-user-config.xml: |
          <clickhouse>
              <profiles>
                  <default>
                      <query_plan_optimize_prewhere>0</query_plan_optimize_prewhere>
                  </default>
              </profiles>
          </clickhouse>
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: k8s.pascaliske.dev/location
                  operator: In
                  values:
                    - public
    tolerations:
      - key: k8s.pascaliske.dev/location
        operator: Equal
        value: public
        effect: NoSchedule
  interval: 10m0s
