---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: clickhouse
  namespace: clickhouse
spec:
  chart:
    spec:
      chart: clickhouse
      version: '0.2.3'
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: pascaliske
        namespace: flux-system
  install:
    createNamespace: true
  values:
    image:
      repository: clickhouse/clickhouse-server
      tag: 23.2.4.12-alpine
    env:
      - name: TZ
        value: ${TIMEZONE}
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: k8s.pascaliske.dev/location
                  operator: In
                  values:
                    - public
    tolerations:
      - key: k8s.pascaliske.dev/location
        operator: Equal
        value: public
        effect: NoSchedule
  interval: 10m0s
