{
 "title": "Pi-hole",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Unique Clients",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "pihole_unique_clients" }
   ]
  },
  {
   "title": "Unique Domains",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "pihole_unique_domains" }
   ]
  },
  {
   "title": "Blocklist",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "pihole_domains_being_blocked" }
   ]
  },
  {
   "title": "Percentage Blocked",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "pihole_ads_percentage_today" }
   ]
  },
  {
   "title": "Percentage Blocked History",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expr": "pihole_ads_percentage_today", "legendFormat": "Percentage Blocked" }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "pihole_dns_queries_today", "legendFormat": "Queries" },
    { "expr": "pihole_ads_blocked_today", "legendFormat": "Blocked" }
   ]
  },
  {
   "title": "Forward Destinations",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 4, "x": 16, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (target) (label_replace(pihole_forward_destinations, \"target\", \"$1\", \"destination\", \".*\\\\|(.*)\"))",
     "legendFormat": "{{ target }}"
    }
   ]
  },
  {
   "title": "Query Types",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "pihole_querytypes", "legendFormat": "{{ type }}" }
   ]
  },
  {
   "title": "Top Domains",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (domain) (pihole_top_queries)",
     "legendFormat": "{{ domain }}"
    }
   ]
  },
  {
   "title": "Top Ads",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (domain) (pihole_top_ads)",
     "legendFormat": "{{ domain }}"
    }
   ]
  },
  {
   "title": "Top Clients",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (ip) (label_replace(pihole_top_sources, \"ip\", \"$1\", \"source\", \".*?([0-9]{1,3}\\\\.[0-9]{1,3}\\\\.[0-9]{1,3}\\\\.[0-9]{1,3}).*?\"))",
     "legendFormat": "{{ hostname }}"
    }
   ]
  }
 ]
}