# install additional tooling
- name: Install additional tooling
  shell:
    cmd: '{{ item }}'
  changed_when: true
  loop:
    - curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash

# setup shell aliases
- name: Setup shell aliases
  lineinfile:
    path: '{{ ansible_env.HOME }}/.bashrc'
    line: 'alias {{ item.alias }}="{{ item.command }}"'
    regexp: 'alias {{ item.alias }}="{{ item.command }}"$'
    insertafter: ^alias
    create: true
  loop:
    - { alias: 'kubectl', command: 'kubectl --kubeconfig {{ k3s_kubeconfig_system }}' }
    - { alias: 'k', command: 'kubectl --kubeconfig {{ k3s_kubeconfig_system }}' }
    - { alias: 'helm', command: 'helm --kubeconfig {{ k3s_kubeconfig_system }}' }
    - { alias: 'h', command: 'helm --kubeconfig {{ k3s_kubeconfig_system }}' }

# configure remote access
- name: Configure remote access
  become: true
  block:
    - name: Change ownership of system config file
      file:
        path: '{{ k3s_kubeconfig_system }}'
        owner: '{{ ansible_user }}'
    - name: Ensure directory exists
      file:
        path: '{{ k3s_kubeconfig_remote | dirname }}'
        state: directory
    - name: Duplicate config file for remote access
      copy:
        src: '{{ k3s_kubeconfig_system }}'
        dest: '{{ k3s_kubeconfig_remote }}'
        owner: '{{ ansible_user }}'
        mode: '0600'
        remote_src: true
    - name: Replace server in config file
      replace:
        path: '{{ k3s_kubeconfig_remote }}'
        regexp: '127\.0\.0\.1'
        replace: '{{ ansible_host }}'
    - name: Fetch config file for remote access
      fetch:
        src: '{{ k3s_kubeconfig_remote }}'
        dest: '{{ k3s_kubeconfig_local }}'
        flat: true
