---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgresql
  namespace: semaphore
spec:
  instances: 1
  primaryUpdateStrategy: unsupervised
  storage:
    size: 1Gi
  superuserSecret:
    name: postgresql-superuser
  bootstrap:
    initdb:
      database: semaphore
      owner: semaphore
      secret:
        name: postgresql-user
  monitoring:
    enablePodMonitor: true
