---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: metallb-crds
  namespace: flux-system
spec:
  sourceRef:
    kind: GitRepository
    name: metallb-source
  interval: 15m
  prune: false
  healthChecks:
    - apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      name: bfdprofiles.metallb.io
    - apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      name: bgpadvertisements.metallb.io
    - apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      name: bgppeers.metallb.io
    - apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      name: communities.metallb.io
    - apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      name: ipaddresspools.metallb.io
    - apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      name: l2advertisements.metallb.io
    - apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      name: servicebgpstatuses.metallb.io
    - apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      name: servicel2statuses.metallb.io
