# configure unattended upgrades
- name: Configure unattended-upgrades
  become: true
  template:
    src: unattended-upgrades/{{ item }}.j2
    dest: /etc/apt/apt.conf.d/{{ item }}
    mode: '0644'
  loop:
    - 10periodic
    - 50unattended-upgrades
