---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: redis
  namespace: redis
spec:
  chart:
    spec:
      chart: redis
      version: '2.0.0'
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: pascaliske
        namespace: flux-system
  values:
    image:
      repository: redis
      tag: 7.4.4-alpine
  interval: 10m0s
