---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: unbound
  namespace: unbound
spec:
  chart:
    spec:
      chart: unbound
      version: '2.0.0'
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: pascaliske
        namespace: flux-system
  values:
    image:
      repository: ghcr.io/pascaliske/unbound
      tag: '0.1.0'
    controller:
      replicas: 2
    env:
      - name: TZ
        value: ${TIMEZONE}
    affinity:
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
                - key: app.kubernetes.io/name
                  operator: In
                  values:
                    - unbound
            topologyKey: kubernetes.io/hostname
  interval: 10m0s

