---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: unbound
  namespace: unbound
spec:
  chartRef:
    kind: OCIRepository
    name: unbound
    namespace: flux-system
  values:
    image:
      repository: ghcr.io/pascaliske/unbound
      tag: '0.2.0'
    controller:
      replicas: 2
    env:
      - name: TZ
        value: ${TIMEZONE}
    affinity:
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
                - key: app.kubernetes.io/name
                  operator: In
                  values:
                    - unbound
            topologyKey: kubernetes.io/hostname
  interval: 10m0s

