---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tailscale-operator
  namespace: tailscale-operator
spec:
  chart:
    spec:
      chart: tailscale-operator
      version: '1.90.9'
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: tailscale
        namespace: flux-system
  install:
    crds: Skip
  upgrade:
    crds: Skip
  values:
    oauth:
      clientId: ${TAILSCALE_OAUTH_CLIENT_ID}
      clientSecret: ${TAILSCALE_OAUTH_CLIENT_SECRET}
    installCRDs: false
    operatorConfig:
      image:
        repository: ghcr.io/tailscale/k8s-operator
        tag: 'v1.90.9'
  interval: 10m0s
