# disable swap
- name: Disable swap
  when: arm
  become: true
  block:
    - name: Clear swap
      command: swapoff -a
    - name: Stop swap service
      service:
        name: dphys-swapfile
        state: stopped
      ignore_errors: true
      register: stop_swap_errors
    - name: Disable swap service
      systemd:
        name: dphys-swapfile
        enabled: false
      ignore_errors: true
      register: disable_swap_errors
    - name: Uninstall swap service
      apt:
        name: dphys-swapfile
        state: absent
        purge: true
