---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: trivy-operator-crds
  namespace: flux-system
spec:
  sourceRef:
    kind: GitRepository
    name: trivy-operator-source
  interval: 15m
  prune: false
  healthChecks:
    - apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      name: clustercompliancereports.aquasecurity.github.io
    - apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      name: clusterconfigauditreports.aquasecurity.github.io
    - apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      name: clusterinfraassessmentreports.aquasecurity.github.io
    - apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      name: clusterrbacassessmentreports.aquasecurity.github.io
    - apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      name: clustersbomreports.aquasecurity.github.io
    - apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      name: configauditreports.aquasecurity.github.io
    - apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      name: exposedsecretreports.aquasecurity.github.io
    - apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      name: infraassessmentreports.aquasecurity.github.io
    - apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      name: rbacassessmentreports.aquasecurity.github.io
    - apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      name: sbomreports.aquasecurity.github.io
    - apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      name: vulnerabilityreports.aquasecurity.github.io
