{
 "title": "Alerts",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Active Alerts",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(alertmanager_alerts{state=\"active\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Suppressed Alerts",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(alertmanager_alerts{state=\"suppressed\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Unprocessed Alerts",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(alertmanager_alerts{state=\"unprocessed\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active Silences",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "alertmanager_silences{state=\"active\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Expired Silences",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "alertmanager_silences{state=\"expired\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pending Silences",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "alertmanager_silences{state=\"pending\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Notifications",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 3 },
   "targets": [
    {
     "expr": "sum by(integration) (increase(alertmanager_notifications_total{integration=~\"discord|email\"}[$__interval]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(integration) (increase(alertmanager_notifications_failed_total{integration=~\"discord|email\"}[$__interval]))",
     "legendFormat": "{{integration}} (failed)"
    }
   ]
  },
  {
   "title": "Notification durations",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (integration) (histogram_quantile(0.99, rate(alertmanager_notification_latency_seconds_bucket{integration=~\"discord|email\"}[$__interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Alerts", "type": "alertlist", "gridPos": { "h": 13, "w": 24, "x": 0, "y": 9 } }
 ]
}