{
 "title": "Pods",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "node",
    "label": "Node",
    "query": {
     "query": "label_values(kube_node_info, node)"
    }
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(container_start_time_seconds{node=~\"[[node]]\"}, namespace)"
    }
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": {
     "query": "label_values(container_start_time_seconds{node=~\"[[node]]\",namespace=~\"[[namespace]]\"}, pod)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "CPU Usage ($node)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg by (pod) (irate(container_cpu_usage_seconds_total{pod=~\"$pod\",node=~\"$node\"}[5m])) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage ($node)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "avg by (pod) (container_memory_usage_bytes{pod=~\"$pod\",node=~\"$node\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk Reads ($node)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by (pod) (rate(container_fs_reads_bytes_total{pod=~\"$pod\",node=~\"$node\"}[$__rate_interval]))",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Ages ($node)",
   "type": "table",
   "gridPos": { "h": 16, "w": 8, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "targets": [
    {
     "expr": "time() - min by (pod, namespace, instance) (container_start_time_seconds{pod!=\"\",node=~\"$node\",namespace=~\"$namespace\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk Writes ($node)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by (pod) (rate(container_fs_writes_bytes_total{pod=~\"$pod\",node=~\"$node\"}[$__rate_interval]))",
     "legendFormat": "{{ pod }}"
    }
   ]
  }
 ]
}