---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - helm-release.yaml
  - silences.yaml
  - certificate.yaml
  - route.yaml
  - middlewares
  - dashboard
