---
# expected as the klipper-lb does not allow specifying tolerations
apiVersion: monitoring.giantswarm.io/v1alpha1
kind: Silence
metadata:
  name: daemonset-misscheduled-traefik-service
  namespace: traefik
spec:
  owner: ${AUTH_USERNAME}
  matchers:
    - name: alertname
      value: KubeDaemonSetMisScheduled
    - name: daemonset
      value: '^svclb-traefik-.*'
      isRegex: true
---
# expected as the klipper-lb does not allow specifying tolerations
apiVersion: monitoring.giantswarm.io/v1alpha1
kind: Silence
metadata:
  name: daemonset-rollout-stuck-traefik-service
  namespace: traefik
spec:
  owner: ${AUTH_USERNAME}
  matchers:
    - name: alertname
      value: KubeDaemonSetRolloutStuck
    - name: daemonset
      value: '^svclb-traefik-.*'
      isRegex: true
