{
 "title": "Internet",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "interval",
    "label": "Interval",
    "query": "5m,15m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "Connection",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Downstream",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "homeassistant_sensor_unit_percent{entity=\"sensor.fritz_box_downstream_percentage\"}"
    }
   ]
  },
  {
   "title": "Upstream",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "homeassistant_sensor_unit_percent{entity=\"sensor.fritz_box_upstream_percentage\"}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "fritzbox_ppp_connection_uptime" }
   ]
  },
  {
   "title": "Speed Test",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Download",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 19, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "avg by (app_kubernetes_io_name) (avg_over_time(speedtest_download_bits_per_second[$interval]))",
     "legendFormat": "Download"
    }
   ]
  },
  {
   "title": "Average Download",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (app_kubernetes_io_name) (avg_over_time(speedtest_download_bits_per_second[$__range]))"
    }
   ]
  },
  {
   "title": "Current Download",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "speedtest_download_bits_per_second"
    }
   ]
  },
  {
   "title": "Upload",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 19, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "avg by (app_kubernetes_io_name) (avg_over_time(speedtest_upload_bits_per_second[$interval]))",
     "legendFormat": "Upload"
    }
   ]
  },
  {
   "title": "Average Upload",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (app_kubernetes_io_name) (avg_over_time(speedtest_upload_bits_per_second[$__range]))"
    }
   ]
  },
  {
   "title": "Current Upload",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "speedtest_upload_bits_per_second"
    }
   ]
  },
  {
   "title": "Ping",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 19, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg by (app_kubernetes_io_name) (avg_over_time(speedtest_ping_latency_milliseconds[$interval]))",
     "legendFormat": "Ping"
    },
    {
     "expr": "avg by (app_kubernetes_io_name) (avg_over_time(speedtest_jitter_latency_milliseconds[$interval]))",
     "legendFormat": "Jitter"
    }
   ]
  },
  {
   "title": "Average Ping",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (app_kubernetes_io_name) (avg_over_time(speedtest_ping_latency_milliseconds[$__range]))"
    }
   ]
  },
  {
   "title": "Current Ping",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "speedtest_ping_latency_milliseconds"
    }
   ]
  }
 ]
}