---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vikunja
  namespace: vikunja
spec:
  chart:
    spec:
      chart: vikunja
      version: '5.0.0'
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: pascaliske
        namespace: flux-system
  install:
    createNamespace: true
  values:
    image:
      repository: vikunja/vikunja
      tag: 0.23.0
    serviceMonitor:
      enabled: true
    ingressRoute:
      create: true
      entryPoints:
        - https
      rule: Host(`tasks.${DOMAIN_EXTERNAL}`)
      middlewares:
        - name: auth
          namespace: traefik
        - name: security
          namespace: traefik
        - name: optimizations
          namespace: traefik
        - name: error-pages
          namespace: traefik-errors
    certificate:
      create: true
      dnsNames:
        - tasks.${DOMAIN_EXTERNAL}
      issuerRef:
        kind: ClusterIssuer
        name: lets-encrypt-production
    env:
      - name: TZ
        value: ${TIMEZONE}
      - name: PGID
        value: '${GID}'
      - name: PUID
        value: '${UID}'
      - name: VIKUNJA_LOG_LEVEL
        value: 'warning'
      - name: VIKUNJA_LOG_HTTP
        value: 'off'
      - name: VIKUNJA_DATABASE_TYPE
        value: postgres
      - name: VIKUNJA_DATABASE_HOST
        value: postgresql-rw
      - name: VIKUNJA_DATABASE_DATABASE
        value: vikunja
      - name: VIKUNJA_DATABASE_USER
        valueFrom:
          secretKeyRef:
            name: postgresql-user
            key: username
      - name: VIKUNJA_DATABASE_PASSWORD
        valueFrom:
          secretKeyRef:
            name: postgresql-user
            key: password
      - name: VIKUNJA_CACHE_ENABLED
        value: 'true'
      - name: VIKUNJA_CACHE_TYPE
        value: redis
      - name: VIKUNJA_REDIS_ENABLED
        value: 'true'
      - name: VIKUNJA_REDIS_HOST
        value: redis.redis.svc.cluster.local:6379
      - name: VIKUNJA_KEYVALUE_TYPE
        value: redis
      - name: VIKUNJA_MAILER_ENABLED
        value: 'true'
      - name: VIKUNJA_MAILER_HOST
        value: '${SMTP_HOST}'
      - name: VIKUNJA_MAILER_PORT
        value: '587'
      - name: VIKUNJA_MAILER_USERNAME
        value: '${SMTP_ACCOUNT_VIKUNJA_EMAIL}'
      - name: VIKUNJA_MAILER_PASSWORD
        value: '${SMTP_ACCOUNT_VIKUNJA_PASSWORD}'
      - name: VIKUNJA_MAILER_FROMEMAIL
        value: '${SMTP_ACCOUNT_VIKUNJA_EMAIL}'
      - name: VIKUNJA_SERVICE_ENABLEEMAILREMINDERS
        value: 'false'
  interval: 10m0s
