---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: loki
  namespace: monitoring
spec:
  chart:
    spec:
      chart: loki
      version: '6.6.2'
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
  install:
    createNamespace: true
  values:
    deploymentMode: SingleBinary
    loki:
      image:
        repository: grafana/loki
        tag: '3.0.0'
      auth_enabled: false
      storage:
        type: filesystem
    test:
      enabled: false
    lokiCanary:
      enabled: false
    gateway:
      enabled: false
    singleBinary:
      # workaround to fix helm error due to weird default value of zero replicas: https://github.com/grafana/loki/issues/8443#issuecomment-1421636858
      replicas: 1
      extraArgs:
        - -config.expand-env=true
        - -log.level=warn
      extraEnv:
        - name: TZ
          value: ${TIMEZONE}
      persistence:
        storageClass: local-path
    monitoring:
      serviceMonitor:
        enabled: true
  interval: 10m0s
