---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: loki
  namespace: monitoring
spec:
  chart:
    spec:
      chart: loki
      version: '6.3.3'
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
  install:
    createNamespace: true
  values:
    loki:
      image:
        repository: grafana/loki
        tag: '3.0.0'
      auth_enabled: false
      commonConfig:
        replication_factor: 1
      storage:
        type: filesystem
      # workaround to fix invalid ruler config error
      rulerConfig:
        storage:
          type: local
    test:
      enabled: false
    monitoring:
      serviceMonitor:
        # disabled due to requirement of grafana operator: https://github.com/grafana/loki/issues/7546
        enabled: false
      selfMonitoring:
        enabled: false
        grafanaAgent:
          installOperator: false
      lokiCanary:
        enabled: false
    singleBinary:
      # workaround to fix helm error due to weird default value of zero replicas: https://github.com/grafana/loki/issues/8443#issuecomment-1421636858
      replicas: 1
      extraArgs:
        - -config.expand-env=true
        - -log.level=warn
      extraEnv:
        - name: TZ
          value: ${TIMEZONE}
      persistence:
        storageClass: local-path
    gateway:
      enabled: false
  interval: 10m0s
