{
 "title": "Docker",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "service",
    "label": "Service",
    "query": {
     "query": "label_values(container_memory_usage_bytes, container_label_com_docker_compose_service)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Container CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by (container_label_com_docker_compose_service) (irate(container_cpu_usage_seconds_total{container_label_com_docker_compose_project=\"network\",container_label_com_docker_compose_service=~\"$service\"}[5m])) * 100",
     "legendFormat": "{{ container_label_com_docker_compose_service }}"
    }
   ]
  },
  {
   "title": "Container Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by (container_label_com_docker_compose_service) (container_memory_usage_bytes{container_label_com_docker_compose_project=\"network\",container_label_com_docker_compose_service=~\"$service\"})",
     "legendFormat": "{{ container_label_com_docker_compose_service }}"
    }
   ]
  },
  {
   "title": "Container Updates",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 },
   "targets": [
    { "expr": "watchtower_containers_scanned", "legendFormat": "Scanned" },
    { "expr": "watchtower_containers_updated", "legendFormat": "Updated" },
    { "expr": "watchtower_containers_failed", "legendFormat": "Failed" }
   ]
  }
 ]
}