{
 "title": "UniFi",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Clients / Guests",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "unifipoller_site_users{subsystem=\"wlan\"}",
     "legendFormat": "Clients"
    },
    {
     "expr": "unifipoller_site_guests{subsystem=\"wlan\"}",
     "legendFormat": "Guests"
    }
   ]
  },
  {
   "title": "Device CPU Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "unifipoller_device_cpu_utilization_ratio",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Device Memory Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "unifipoller_device_memory_utilization_ratio",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "PoE Consumption",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "expr": "unifipoller_device_port_poe_watts",
     "legendFormat": "{{ port_name }} (#{{ port_num }})"
    }
   ]
  }
 ]
}