---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: pairdrop
  namespace: pairdrop
spec:
  chart:
    spec:
      chart: pairdrop
      version: '1.0.2'
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: pascaliske
        namespace: flux-system
  values:
    image:
      registry: ghcr.io
      repository: linuxserver/pairdrop
      tag: version-v1.11.2
    ingressRoute:
      create: true
      entryPoints:
        - https
      rule: Host(`drop.${DOMAIN_INTERNAL}`)
      middlewares:
        - name: security
          namespace: traefik
        - name: optimizations
          namespace: traefik
        - name: error-pages
          namespace: traefik-errors
    certificate:
      create: true
      dnsNames:
        - drop.${DOMAIN_INTERNAL}
      issuerRef:
        kind: ClusterIssuer
        name: lets-encrypt-production
    env:
      - name: TZ
        value: ${TIMEZONE}
    resources:
      limits:
        cpu: 100m
        memory: 128Mi
      requests:
        cpu: 100m
        memory: 128Mi
  interval: 10m0s
