{
 "title": "DNS",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "pod",
    "label": "Pod",
    "query": {
     "query": "label_values(blocky_build_info, pod)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Version",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "blocky_build_info{pod=~\"$pod\"}"
    }
   ]
  },
  {
   "title": "DNS Prefetch Count",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ceil(sum(increase(blocky_prefetch_count{pod=~\"$pod\"}[$__range])))"
    }
   ]
  },
  {
   "title": "Last List Refresh",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - blocky_last_list_group_refresh{pod=~\"$pod\"}"
    }
   ]
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Total Queries",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "sum(rate(blocky_query_total{pod=~\"$pod\"}[$__range])) by (pod)",
     "legendFormat": "{{ kubernetes_pod_name }}"
    }
   ]
  },
  {
   "title": "Blocked Queries",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "targets": [
    {
     "expr": "sum(rate(blocky_response_total{response_type=\"BLOCKED\",pod=~\"$pod\"}[$__range])) by (pod)",
     "legendFormat": "{{ kubernetes_pod_name }}"
    }
   ]
  },
  {
   "title": "Average Response Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(rate(blocky_request_duration_ms_sum{pod=~\"$pod\"}[$__range])) / sum(rate(blocky_request_duration_ms_count{pod=~\"$pod\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Cache Ratio",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "targets": [
    {
     "expr": "sum(increase(blocky_cache_hit_count{pod=~\"$pod\"}[$__range])) / (sum(increase(blocky_cache_hit_count{pod=~\"$pod\"}[$__range])) + sum(increase(blocky_cache_miss_count{pod=~\"$pod\"}[$__range])))"
    }
   ]
  }
 ]
}