---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: gitlab-runner
  namespace: gitlab
spec:
  chart:
    spec:
      chart: gitlab-runner
      version: '0.85.0'
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: gitlab
        namespace: flux-system
  values: # defaults: https://gitlab.com/gitlab-org/charts/gitlab-runner/-/blob/main/values.yaml
    fullnameOverride: gitlab-runner
    imagePullSecrets:
      - name: gitlab-registry-auth
    replicas: 1
    gitlabUrl: https://git.${DOMAIN_EXTERNAL}
    runnerToken: ${GITLAB_RUNNER_TOKEN}
    unregisterRunners: true
    concurrent: 2
    logLevel: info
    sentryDsn: ${SENTRY_DSN_LEGACY}
    rbac:
      create: true
    serviceAccount:
      imagePullSecrets:
        - gitlab-registry-auth
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
    service:
      enabled: true
    runners:
      name: BB-8
      executor: kubernetes
      secret: gitlab-runner-tokens
      config: |
        [[runners]]
          [runners.cache]
            [runners.cache.s3]
            [runners.cache.gcs]
          [runners.kubernetes]
            namespace = "{{ default .Release.Namespace .Values.runners.jobNamespace }}"
            image = "alpine:latest"
            image_pull_secrets = ["gitlab-registry-auth"]
            helper_image = "registry.gitlab.com/gitlab-org/gitlab-runner/gitlab-runner-helper:x86_64-v18.8.0"
            pull_policy = ["always", "if-not-present"]
          [runners.feature_flags]
            FF_USE_ADAPTIVE_REQUEST_CONCURRENCY = true
  interval: 10m0s
