---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: authelia
  namespace: authelia
spec:
  chart:
    spec:
      chart: authelia
      version: '0.8.58'
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: authelia
        namespace: flux-system
  install:
    createNamespace: true
  values:
    image:
      registry: ghcr.io
      repository: authelia/authelia
      tag: '4.37.5'
    domain: ${DOMAIN_INTERNAL}
    pod:
      kind: Deployment
      env:
        - name: TZ
          value: ${TIMEZONE}
      extraVolumeMounts:
        - name: users
          mountPath: /users.yaml
          subPath: users.yaml
          readOnly: true
      extraVolumes:
        - name: users
          configMap:
            name: authelia-users
            items:
              - key: users.yaml
                path: users.yaml
    configMap:
      log:
        level: info
      telemetry:
        metrics:
          enabled: true
          serviceMonitor:
            enabled: true
      default_redirection_url: https://${DOMAIN_INTERNAL}
      theme: dark
      webauthn:
        display_name: auth@infrastructure
      authentication_backend:
        password_reset:
          disable: true
        ldap:
          enabled: false
        file:
          enabled: true
          path: /users.yaml
          search:
            email: true
          password:
            algorithm: argon2
      access_control:
        secret:
          enabled: true
        rules:
          - policy: bypass
            domain:
              - unifi.${DOMAIN_INTERNAL}
              - vault.${DOMAIN_INTERNAL}
          - policy: bypass
            domain: blocky.${DOMAIN_INTERNAL}
            resources:
              - /dns-query
          - policy: bypass
            domain: loki.${DOMAIN_INTERNAL}
            resources:
              - /ready
              - /loki/api/v1/push
          - policy: bypass
            domain: homeassistant.${DOMAIN_INTERNAL}
            resources:
              - /api/services
              - /api/websocket
          - policy: two_factor
            domain: vault.${DOMAIN_INTERNAL}
            subject:
              - group:admins
            resources:
              - /admin
          - policy: one_factor
            domain: homeassistant.${DOMAIN_INTERNAL}
            subject:
              - group:family
          - policy: two_factor
            domain:
              - ${DOMAIN_INTERNAL}
              - '*.${DOMAIN_INTERNAL}'
            subject:
              - group:admins
      session:
        inactivity: 10m
        redis:
          host: redis.redis.svc.cluster.local
      storage:
        local:
          enabled: true
          path: /config/db.sqlite3
        postgres:
          enabled: false
      notifier:
        smtp:
          enabledSecret: true
          host: ${SMTP_HOST}
          port: 587
          username: ${SMTP_ACCOUNT_AUTH_EMAIL}
          sender: ${SMTP_ACCOUNT_AUTH_EMAIL}
          subject: '[auth@infrastructure] {title}'
      identity_providers:
        oidc:
          enabled: true
          clients:
            - id: synology-dsm
              description: Synology DSM
              secret: '${AUTH_OIDC_CLIENT_SECRET_HASH}'
              public: false
              authorization_policy: two_factor
              redirect_uris:
                - https://ryloth.${DOMAIN_INTERNAL}
              scopes:
                - openid
                - profile
                - groups
                - email
              userinfo_signing_algorithm: none
    secret:
      jwt:
        value: ${AUTH_JWT_SECRET}
      storageEncryptionKey:
        value: ${AUTH_STORAGE_SECRET}
      session:
        value: ${AUTH_SESSION_SECRET}
      smtp:
        value: ${SMTP_ACCOUNT_AUTH_PASSWORD}
    persistence:
      enabled: true
      storageClass: local-path
  interval: 10m0s

