---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: homer
  namespace: homer
spec:
  chart:
    spec:
      chart: homer
      version: '1.0.4'
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: pascaliske
        namespace: flux-system
  install:
    createNamespace: true
  values:
    image:
      repository: ghcr.io/bastienwirtz/homer
      tag: v23.09.1
    ingressRoute:
      create: true
      entryPoints:
        - https
      rule: Host(`${DOMAIN_INTERNAL}`)
      middlewares:
        - name: auth
          namespace: traefik
        - name: security
          namespace: traefik
        - name: optimizations
          namespace: traefik
        - name: error-pages
          namespace: traefik-errors
    certificate:
      create: true
      dnsNames:
        - ${DOMAIN_INTERNAL}
      issuerRef:
        kind: ClusterIssuer
        name: lets-encrypt-production
    env:
      - name: TZ
        value: ${TIMEZONE}
    securityContext:
      runAsNonRoot: true
      runAsGroup: ${GID}
      runAsUser: ${UID}
  valuesFrom:
    - kind: ConfigMap
      name: homer-config
      valuesKey: config.yml
      targetPath: configMap.config
  interval: 10m0s
