---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kured
  namespace: kured
spec:
  chart:
    spec:
      chart: kured
      version: '5.4.5'
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: kured
        namespace: flux-system
  install:
    createNamespace: true
  values:
    image:
      repository: ghcr.io/kubereboot/kured
      tag: 1.15.1
    extraEnvVars:
      - name: TZ
        value: ${TIMEZONE}
    configuration:
      timeZone: ${TIMEZONE}
      rebootDays: ['fr', 'sa', 'su']
      startTime: '22:00'
      blockingPodSelector:
        - app.kubernetes.io/name=paperless
        - app.kubernetes.io/name=home-assistant
        - app.kubernetes.io/name=gitlab
    metrics:
      create: true
    service:
      create: true
    tolerations:
      - key: node-role.kubernetes.io/control-plane
        effect: NoSchedule
      - key: k8s.pascaliske.dev/location
        operator: Equal
        value: public
        effect: NoSchedule
  interval: 10m0s
