---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kured
  namespace: kured
spec:
  chart:
    spec:
      chart: kured
      version: '5.2.0'
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: kured
        namespace: flux-system
  install:
    createNamespace: true
  values:
    image:
      repository: ghcr.io/kubereboot/kured
      tag: 1.14.1
    extraEnvVars:
      - name: TZ
        value: ${TIMEZONE}
    configuration: {}
    metrics:
      create: true
    service:
      create: true
    tolerations:
      - key: k8s.pascaliske.dev/location
        operator: Equal
        value: public
        effect: NoSchedule
  interval: 10m0s
