---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: home-assistant
  namespace: home-assistant
spec:
  chart:
    spec:
      chart: home-assistant
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
  install:
    createNamespace: true
  values:
    image:
      repository: ghcr.io/home-assistant/home-assistant
      tag: '2023.3.1'

    imagePullSecrets:
      - name: github-registry

    env:
      - name: TZ
        value: ${TIMEZONE}

    # needed for homekit, wake-on-lan and ps4 integrations
    hostNetwork: true

    # needed as workaround for dns issues with host network
    dnsPolicy: ClusterFirst

    # needed for zigbee usb access
    securityContext:
      privileged: true

    initContainers:
      init-config:
        image: ghcr.io/pascaliske/home-assistant:master
        env:
          - name: GIT_SYNC_ONE_TIME
            value: 'true'
        volumeMounts:
          - name: config
            mountPath: /config
          - name: config-sync
            mountPath: /config-sync
    additionalContainers:
      sync-config:
        image: ghcr.io/pascaliske/home-assistant:master
        volumeMounts:
          - name: config
            mountPath: /config
          - name: config-sync
            mountPath: /config-sync

    persistence:
      config:
        enabled: true
        type: hostPath
        hostPath: ${PATH_HOME}/home-assistant
        mountPath: /config
      config-sync:
        enabled: true
        type: emptyDir
        mountPath: /config-sync
      secrets:
        enabled: true
        type: secret
        mountPath: /config/secrets.yaml
        subPath: secrets.yaml
        name: secrets
      usb:
        enabled: true
        type: hostPath
        hostPath: /dev/ttyACM0
    metrics:
      enabled: true
      serviceMonitor:
        bearerTokenSecret:
          name: monitoring-auth
          key: token
      prometheusRule:
        enabled: true

    # ensure pod runs on node with conbee stick attached
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: k8s.pascaliske.dev/hardware
                  operator: In
                  values:
                    - zigbee
  interval: 10m0s
