---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: silence-operator-crds
  namespace: flux-system
spec:
  sourceRef:
    kind: GitRepository
    name: silence-operator-source
  interval: 15m
  prune: false
  healthChecks:
    - apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      name: silences.monitoring.giantswarm.io
