---
# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: '3'

tasks:
  # generate documentation pages
  general-pages:
    cmds:
      - cat README.md > docs/index.md
      - echo "---" > docs/LICENSE.md
      - echo "hide:" >> docs/LICENSE.md
      - echo "  - navigation" >> docs/LICENSE.md
      - echo "---" >> docs/LICENSE.md
      - cat LICENSE.md > docs/LICENSE.md

  cluster-pages:
    dir: clusters/production
    cmds:
      - for file in **/README.md; do mkdir -p ../../docs/cluster/$(dirname $file) && cp $file ../../docs/cluster/$(dirname $file)/index.md; done
      - for file in **/**/README.md; do mkdir -p ../../docs/cluster/$(dirname $file) && cp $file ../../docs/cluster/$(dirname $file)/index.md; done
      - for file in **/**/**/README.md; do mkdir -p ../../docs/cluster/$(dirname $file) && cp $file ../../docs/cluster/$(dirname $file)/index.md; done

  # serve documentation for development purposes
  serve:
    cmds:
      - docker run --rm -it -p 8000:8000 -v $(pwd):/docs squidfunk/mkdocs-material
