# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: '3'

tasks:
  init:
    dir: terraform
    cmds:
      - terraform init {{.CLI_ARGS}}
  plan:
    dir: terraform
    cmds:
      - terraform plan {{.CLI_ARGS}}
  apply:
    dir: terraform
    cmds:
      - terraform apply {{.CLI_ARGS}}
  destroy:
    dir: terraform
    cmds:
      - terraform destroy {{.CLI_ARGS}}
  show:
    dir: terraform
    cmds:
      - terraform show {{.CLI_ARGS}}
  output:
    dir: terraform
    cmds:
      - terraform output --raw {{.CLI_ARGS}}
  format:
    dir: terraform
    cmds:
      - terraform fmt {{.CLI_ARGS}}
  validate:
    dir: terraform
    cmds:
      - terraform validate {{.CLI_ARGS}}
  lint:
    dir: terraform
    cmds:
      - tflint --format compact
  docs:
    dir: terraform
    cmds:
      - terraform-docs markdown --output-file README.md .
