# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: '3'

tasks:
  init:
    dir: terraform
    cmds:
      - terraform init {{.CLI_ARGS}}
  plan:
    dir: terraform
    cmds:
      - terraform plan {{.CLI_ARGS}}
  apply:
    dir: terraform
    cmds:
      - terraform apply {{.CLI_ARGS}}
  format:
    dir: terraform
    cmds:
      - terraform fmt {{.CLI_ARGS}}
  validate:
    dir: terraform
    cmds:
      - terraform validate {{.CLI_ARGS}}
  lint:
    dir: terraform
    cmds:
      - tflint --format compact
