---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: gitlab-runner
  namespace: gitlab
spec:
  chart:
    spec:
      chart: gitlab-runner
      version: '0.81.0'
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: gitlab
        namespace: flux-system
  values:
    fullnameOverride: gitlab-runner
    imagePullSecrets:
      - name: gitlab-registry-auth
    replicas: 1
    gitlabUrl: https://git.${DOMAIN_EXTERNAL}
    runnerToken: ${GITLAB_RUNNER_TOKEN}
    unregisterRunners: true
    concurrent: 2
    logLevel: info
    sentryDsn: ${SENTRY_DSN_LEGACY}
    rbac:
      create: true
      imagePullSecrets:
        - gitlab-registry-auth
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
    service:
      enabled: true
    runners:
      name: BB-8
      executor: kubernetes
      tags: kubernetes,internal
      secret: gitlab-runner-tokens
      config: |
        [[runners]]
          pre_clone_script = 'cat /etc/resolv.conf | sed -r "s/^(search.*|options.*)/#\1/" > /tmp/resolv && cat /tmp/resolv > /etc/resolv.conf'
          [runners.cache]
            [runners.cache.s3]
            [runners.cache.gcs]
          [runners.kubernetes]
            namespace = "gitlab"
            image = "alpine:latest"
            image_pull_secrets = ["gitlab-registry-auth"]
            helper_image = "registry.gitlab.com/gitlab-org/gitlab-runner/gitlab-runner-helper:ubuntu-arm64-latest"
            pull_policy = ["always", "if-not-present"]
            [runners.kubernetes.dns_config]
              [[runners.kubernetes.dns_config.options]]
                name = "ndots"
                value = "1"
      runUntagged: true
    resources: {}
      # limits:
      #   memory: 256Mi
      #   cpu: 200m
      # requests:
      #   memory: 128Mi
      #   cpu: 100m
  interval: 10m0s
