# check virtual ip variable
- name: Check provided virtual ip
  assert:
    success_msg: The provided virtual ip looks valid.
    fail_msg: The provided virtual ip is empty or has an invalid format!
    that:
      - keepalived_virtual_ip is defined
      - keepalived_virtual_ip is ansible.utils.ipv4

# check auth password variable
- name: Check provided auth password
  assert:
    success_msg: The provided auth password looks valid.
    fail_msg: The provided auth password is empty or has an invalid length!
    that:
      - keepalived_auth_password is defined
      - keepalived_auth_password | length > 0
      - keepalived_auth_password | length < 9

# configure keepalived
- name: Configure keepalived
  become: true
  block:
    - name: Ensure configuration directory exists
      file:
        path: /etc/keepalived
        state: directory
    - name: Create configuration file
      template:
        src: '{{ role_name }}/keepalived.conf.j2'
        dest: /etc/keepalived/keepalived.conf
        validate: /usr/sbin/keepalived --config-test --use-file %s
      notify: Restart keepalived

# install keepalived
- name: Install keepalived
  become: true
  apt:
    name: keepalived
    update_cache: true
    state: latest
