---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: speedtest-exporter
  namespace: monitoring
spec:
  chart:
    spec:
      chart: speedtest-exporter
      version: '5.4.2'
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
  install:
    createNamespace: true
  values:
    image:
      repository: ghcr.io/miguelndecarvalho/speedtest-exporter
      tag: v3.5.4
    env:
      - name: TZ
        value: ${TIMEZONE}
    metrics:
      enabled: true
      serviceMonitor:
        interval: 5m
      prometheusRule:
        enabled: true
  interval: 10m0s
