---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vector
  namespace: monitoring
spec:
  chart:
    spec:
      chart: vector
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: vector
        namespace: flux-system
  install:
    createNamespace: true
  values:
    role: Agent
    image:
      repository: timberio/vector
      tag: 0.25.1-alpine
    env:
      - name: TZ
        value: ${TIMEZONE}
      - name: VECTOR_WATCH_CONFIG
        value: 'true'
    containerPorts:
      - name: api
        containerPort: 8686
        protocol: TCP
      - name: prom-exporter
        containerPort: 9090
        protocol: TCP
    tolerations:
      - key: node-role.kubernetes.io/control-plane
        operator: Exists
        effect: NoSchedule
      - key: k8s.pascaliske.dev/location
        operator: Equal
        value: public
        effect: NoSchedule
    customConfig:
      data_dir: /vector-data-dir
      api:
        enabled: true
        address: 127.0.0.1:8686
        playground: false
      sources:
        kubernetes_logs:
          type: kubernetes_logs
        vector_logs:
          type: internal_logs
        internal_metrics:
          type: internal_metrics
      sinks:
        loki:
          type: loki
          inputs:
            - kubernetes_logs
            - vector_logs
          endpoint: http://loki.monitoring.svc.cluster.local:3100
          encoding:
            codec: text
          remove_label_fields: true
          remove_timestamp: true
          labels:
            source: >-
              {{`{{ source_type }}`}}
            stream: >-
              {{`{{ stream }}`}}
            file: >-
              {{`{{ file }}`}}
            app: >-
              {{`{{ kubernetes.pod_labels.app\.kubernetes\.io/name }}`}}
            node: >-
              {{`{{ kubernetes.pod_node_name }}`}}
            namespace: >-
              {{`{{ kubernetes.pod_namespace }}`}}
            pod: >-
              {{`{{ kubernetes.pod_name }}`}}
            container: >-
              {{`{{ kubernetes.container_name }}`}}
            image: >-
              {{`{{ kubernetes.container_image }}`}}
        prometheus_exporter:
          type: prometheus_exporter
          inputs:
            - internal_metrics
          address: 0.0.0.0:9090
    persistence:
      enabled: true
    podMonitor:
      enabled: true
      port: prom-exporter
  interval: 10m0s
