---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vector
  namespace: monitoring
spec:
  chart:
    spec:
      chart: vector
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: vector
        namespace: flux-system
  install:
    createNamespace: true
  values:
    role: Agent
    image:
      repository: timberio/vector
      tag: 0.33.0-alpine
    env:
      - name: TZ
        value: ${TIMEZONE}
      - name: VECTOR_LOG
        value: WARN
      - name: VECTOR_WATCH_CONFIG
        value: 'true'
    containerPorts:
      - name: api
        containerPort: 8686
        protocol: TCP
      - name: prom-exporter
        containerPort: 9090
        protocol: TCP
    tolerations:
      - key: node-role.kubernetes.io/control-plane
        operator: Exists
        effect: NoSchedule
      - key: k8s.pascaliske.dev/location
        operator: Equal
        value: public
        effect: NoSchedule
    customConfig:
      data_dir: /vector-data-dir
      api:
        enabled: true
        address: 127.0.0.1:8686
        playground: false
      sources:
        vector_metrics_source:
          type: internal_metrics
        vector_logs_source:
          type: internal_logs
        kubernetes_logs_source:
          type: kubernetes_logs
          use_apiserver_cache: true
          pod_annotation_fields:
            pod_labels: pod_labels
            pod_name: pod_name
            pod_annotations: ""
          namespace_annotation_fields:
            namespace_labels: ""
          node_annotation_fields:
            node_labels: ""
        # Note: Not working due to missing `journalctl` binary in Vector image.
        # journald_logs_source:
        #   type: journald
        #   journal_directory: /var/log/journal
      transforms:
        kubernetes_logs_transform:
          type: remap
          inputs:
            - kubernetes_logs_source
          source: |
            # Standardize 'app' index
            .custom_app_name = .pod_labels."app.kubernetes.io/name" || .pod_labels.app || .pod_labels."k8s-app" || "unknown"
            # Drop pod_labels
            del(.pod_labels)
      sinks:
        vector_metrics_sink:
          type: prometheus_exporter
          inputs:
            - vector_metrics_source
          address: 0.0.0.0:9090
        vector_logs_sink:
          type: loki
          inputs:
            - vector_logs_source
          endpoint: http://loki.monitoring.svc.cluster.local:3100
          encoding:
            codec: logfmt
          out_of_order_action: accept
          remove_label_fields: true
          remove_timestamp: true
          labels:
            source: >-
              {{`{{ source_type }}`}}
        kubernetes_logs_sink:
          type: loki
          inputs:
            - kubernetes_logs_transform
          endpoint: http://loki.monitoring.svc.cluster.local:3100
          encoding:
            codec: logfmt
          out_of_order_action: accept
          remove_label_fields: true
          remove_timestamp: true
          labels:
            source: >-
              {{`{{ source_type }}`}}
            stream: >-
              {{`{{ stream }}`}}
            file: >-
              {{`{{ file }}`}}
            app: >-
              {{`{{ custom_app_name }}`}}
            node: >-
              {{`{{ kubernetes.pod_node_name }}`}}
            namespace: >-
              {{`{{ kubernetes.pod_namespace }}`}}
            pod: >-
              {{`{{ kubernetes.pod_name }}`}}
            container: >-
              {{`{{ kubernetes.container_name }}`}}
            image: >-
              {{`{{ kubernetes.container_image }}`}}
        # journald_logs_sink:
        #   type: loki
        #   inputs:
        #     - journald_logs
        #   endpoint: http://loki.monitoring.svc.cluster.local:3100
        #   encoding:
        #     codec: logfmt
        #   out_of_order_action: accept
        #   remove_label_fields: true
        #   remove_timestamp: true
    persistence:
      enabled: true
    podMonitor:
      enabled: true
      port: prom-exporter
  interval: 10m0s
