---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: crowdsec
  namespace: crowdsec
spec:
  chart:
    spec:
      chart: crowdsec
      version: '0.9.12'
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: crowdsec
        namespace: flux-system
  install:
    createNamespace: true
  values:
    container_runtime: containerd
    image:
      repository: ghcr.io/crowdsecurity/crowdsec
      pullPolicy: IfNotPresent
      tag: 'v1.6.0'
    lapi:
      env:
        - name: TZ
          value: ${TIMEZONE}
        - name: ENROLL_INSTANCE_NAME
          value: infrastructure
        # Setting the enroll key after initial startup requires force enrollment which currently breaks the local API.
        # - name: ENROLL_KEY
        #   valueFrom:
        #     secretKeyRef:
        #       name: crowdsec-keys
        #       key: ENROLL_KEY
      dashboard:
        enabled: false # TODO: look for arm image
        image:
          repository: metabase/metabase
          tag: 'v0.48.3'
      metrics:
        enabled: true
        serviceMonitor:
          enabled: true
    agent:
      acquisition:
        - namespace: traefik
          podName: traefik-*
          program: traefik
        - namespace: '*'
          podName: postgresql-*
          program: pgsql
      env:
        - name: TZ
          value: ${TIMEZONE}
        - name: COLLECTIONS
          value: >-
            crowdsecurity/linux
            crowdsecurity/traefik
            crowdsecurity/base-http-scenarios
            crowdsecurity/http-cve
            crowdsecurity/pgsql
        - name: PARSERS
          value: >-
            crowdsecurity/cri-logs
            crowdsecurity/docker-logs
      tolerations:
        - key: node-role.kubernetes.io/control-plane
          operator: Exists
          effect: NoSchedule
        - key: k8s.pascaliske.dev/location
          operator: Equal
          value: public
          effect: NoSchedule
      metrics:
        enabled: true
        serviceMonitor:
          enabled: true
  interval: 10m0s
