---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  chart:
    spec:
      chart: cert-manager
      version: 'v1.16.2'
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: jetstack
        namespace: flux-system
  values:
    installCRDs: false
    extraArgs:
      - --dns01-recursive-nameservers-only
      - --dns01-recursive-nameservers="1.1.1.1:53"
    extraEnv:
      - name: TZ
        value: ${TIMEZONE}
    prometheus:
      enabled: true
      servicemonitor:
        enabled: true
  interval: 10m0s
