---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: blocky
  namespace: blocky
spec:
  chart:
    spec:
      chart: blocky
      version: '11.27.0'
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: johanneskastl
        namespace: flux-system
  values: # defaults: https://github.com/johanneskastl/helm-charts/blob/main/charts/blocky/values.yaml
    image:
      repository: ghcr.io/0xerr0r/blocky
      tag: v0.33.0
    controller:
      replicas: 3
      strategy: RollingUpdate
      rollingUpdate:
        surge: 0
        unavailable: 1
    serviceAccount:
      create: true
    env:
      TZ: ${TIMEZONE}
    podSecurityContext:
      runAsUser: 100
      runAsGroup: 100
      runAsNonRoot: true
      fsGroup: 100
      seccompProfile:
        type: RuntimeDefault
    securityContext:
      privileged: false
      readOnlyRootFilesystem: true
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL
        add:
          - NET_BIND_SERVICE
    service:
      main:
        enabled: true
      dns:
        enabled: true
        type: LoadBalancer
        annotations:
          metallb.io/loadBalancerIPs: 10.0.2.31
    persistence:
      logs:
        enabled: false
        mountPath: /logs
        accessMode: ReadWriteOnce
        size: 512Mi
    metrics:
      enabled: true
      prometheusRule:
        enabled: true
    affinity:
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
                - key: app.kubernetes.io/name
                  operator: In
                  values:
                    - blocky
            topologyKey: kubernetes.io/hostname
  valuesFrom:
    - kind: ConfigMap
      name: blocky-config
      valuesKey: config.yml
      targetPath: config
  interval: 10m0s
