#!/usr/bin/env sh
# -*- coding: utf-8 -*-

# check if vault is encrypted
if (grep -q "\$ANSIBLE_VAULT;" ansible/vars/vault.yml); then
    echo "Vault Encrypted. Safe to commit."
else
    echo "Vault not encrypted! Run 'yr vault:encrypt' and try again."
    exit 1
fi
