---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: descheduler
  namespace: kube-system
spec:
  chart:
    spec:
      chart: descheduler
      version: '0.33.0'
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: descheduler
        namespace: flux-system
  values: # defaults: https://github.com/kubernetes-sigs/descheduler/blob/master/charts/descheduler/values.yaml
    image:
      repository: registry.k8s.io/descheduler/descheduler
      tag: v0.33.0
    schedule: '*/10 * * * *'
    suspend: false
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: node-role.kubernetes.io/control-plane
                  operator: Exists
    tolerations:
      - key: node-role.kubernetes.io/control-plane
        operator: Exists
        effect: NoSchedule
    serviceMonitor:
      enabled: true
  interval: 10m0s
