---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: local-path-provisioner
  namespace: local-path-storage
spec:
  chart:
    spec:
      chart: local-path-provisioner
      version: '0.0.33'
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: local-path-provisioner
        namespace: flux-system
  values: # defaults: https://github.com/rancher/local-path-provisioner/blob/master/deploy/chart/local-path-provisioner/values.yaml
    image:
      repository: docker.io/rancher/local-path-provisioner
      tag: 'v0.0.33'
    helperImage:
      repository: docker.io/library/busybox
      tag: '1.37.0'
    storageClass:
      create: true
      defaultClass: true
      reclaimPolicy: Delete
    nodePathMap:
      - node: DEFAULT_PATH_FOR_NON_LISTED_NODES
        paths:
          - /var/mnt/local-path-provisioner
    podSecurityContext:
      runAsNonRoot: true
    securityContext:
      allowPrivilegeEscalation: false
      seccompProfile:
        type: RuntimeDefault
      capabilities:
        drop:
          - ALL
      runAsUser: 65534
      runAsGroup: 65534
      readOnlyRootFilesystem: true
  interval: 10m0s
