# directories
- name: Ensure directories exist
  file:
    path: '{{ root_path }}/{{ item }}'
    state: directory
  loop:
    - '{{ role_name }}'
    - '{{ role_name }}/data'
    - projects

# code-server
- name: Create configuration file
  template:
    src: '{{ role_name }}/config.yml.j2'
    dest: '{{ root_path }}/{{ role_name }}/config.yml'

# checkout project repositories
- name: Checkout project repositories
  git:
    repo: 'https://github.com/{{ item.user }}/{{ item.repo }}.git'
    dest: '{{ root_path }}/projects/{{ item.repo }}'
    version: '{{ item.ref | default("master") }}'
  loop: '{{ projects }}'
