---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: redis-operator
  namespace: redis-operator
spec:
  chart:
    spec:
      chart: redis-operator
      version: '3.2.9'
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: redis-operator
        namespace: flux-system
  values:
    image:
      repository: quay.io/spotahome/redis-operator
      tag: v1.2.4
    monitoring:
      enabled: true
      serviceMonitor: true
  interval: 10m0s
