# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Build Docs
on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  docs:
    name: Build Docs
    runs-on: ubuntu-latest
    steps:
      # checkout
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      # setup taskfile
      - uses: arduino/setup-task@c0bc642852239c2689f73f4ea6459c29405f3c52 # v3.0.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      # setup cache for social cards
      - uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
        with:
          key: ${{ github.ref }}
          path: .cache

      # create pages for docs
      - name: Create pages for docs
        run: task docs

      # deploy docs
      - uses: mhausenblas/mkdocs-deploy-gh-pages@a31c6b13a80e4a4fbb525eeb7a2a78253bb15fa5 # master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REQUIREMENTS: docs/requirements.txt
