# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Build Docs
on:
  push:
    branches:
      - main

jobs:
  docs:
    name: Build Docs
    runs-on: ubuntu-latest
    steps:
      # checkout
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      # setup taskfile
      - uses: arduino/setup-task@b91d5d2c96a56797b48ac1e0e89220bf64044611 # v2.0.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      # setup cache for social cards
      - uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
        with:
          key: ${{ github.ref }}
          path: .cache

      # create pages for docs
      - name: Create pages for docs
        run: task docs

      # deploy docs
      - uses: mhausenblas/mkdocs-deploy-gh-pages@a31c6b13a80e4a4fbb525eeb7a2a78253bb15fa5 # master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REQUIREMENTS: docs/requirements.txt
