name: Issues
on:
  issues:
    types:
      - opened

jobs:
  issues:
    name: Issues
    runs-on: ubuntu-latest
    steps:
      # add issue to project
      - uses: actions/add-to-project
        with:
          project-url: https://github.com/users/${{ github.repository_owner }}/projects/1
          github-token: ${{ secrets.GITHUB_TOKEN }}