# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Labels
on: push

jobs:
  labels:
    name: Labels
    runs-on: ubuntu-latest
    steps:
      # checkout
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      # sync labels
      - uses: crazy-max/ghaction-github-labeler@548a7c3603594ec17c819e1239f281a3b801ab4d # v6.0.0
        if: success()
