# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Terraform
on:
  push:
    branches:
      - main
    paths:
      - 'terraform/**'
      - '.github/workflows/terraform.yml'
  pull_request:
    branches:
      - main
    paths:
      - 'terraform/**'
      - '.github/workflows/terraform.yml'

permissions:
  contents: read

env:
  TF_INPUT: false
  TF_IN_AUTOMATION: true

jobs:
  linting:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      # checkout
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      # setup taskfile
      - uses: arduino/setup-task@b91d5d2c96a56797b48ac1e0e89220bf64044611 # v2.0.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      # setup terraform
      - uses: hashicorp/setup-terraform@dfe3c3f87815947d99a8997f908cb6525fc44e9e # v4.0.1

      # setup tflint
      - uses: terraform-linters/setup-tflint@6e1e0642c0289bd619021bf6b34e3c08ed1e005a # v6.3.0

      # init terraform
      - name: Init Terraform
        run: task tf:init -- -backend=false

      # validate terraform
      - name: Validate Terraform
        run: task tf:validate

      # lint terraform
      - name: Lint Terraform
        run: task tf:lint
