{
 "title": "Node",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 - (avg by (instance) (irate(node_cpu_seconds_total{job=\"network/node\",mode=\"idle\"}[10m])) * 100)",
     "legendFormat": "Average CPU Usage"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "expr": "node_hwmon_temp_celsius{sensor=\"temp0\"}",
     "legendFormat": "Temperature"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_time_seconds - node_boot_time_seconds"
    }
   ]
  },
  {
   "title": "CPU Cores",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "count without(cpu, mode) (node_cpu_seconds_total{mode=\"idle\"})"
    }
   ]
  },
  {
   "title": "Load 1",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 18, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "node_load1" }
   ]
  },
  {
   "title": "Load 5",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 20, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "node_load5" }
   ]
  },
  {
   "title": "Load 15",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 22, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "node_load15" }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 * (1 - ((avg_over_time(node_memory_MemFree_bytes[24h]) + avg_over_time(node_memory_Cached_bytes[24h]) + avg_over_time(node_memory_Buffers_bytes[24h])) / avg_over_time(node_memory_MemTotal_bytes[24h])))",
     "legendFormat": "Average Memory Usage"
    }
   ]
  },
  {
   "title": "Processes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "node_procs_running", "legendFormat": "running" },
    { "expr": "node_procs_blocked", "legendFormat": "blocked by I/O" }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{device=\"/dev/root\",mountpoint=\"/\"} * 100) / node_filesystem_size_bytes{device=\"/dev/root\",mountpoint=\"/\"})",
     "legendFormat": "Disk Usage"
    }
   ]
  },
  {
   "title": "Network I/O",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{device!=\"lo\"}[1m])",
     "legendFormat": "{{ device }}-in"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{device!=\"lo\"}[1m])",
     "legendFormat": "{{ device }}-out"
    }
   ]
  }
 ]
}