{
 "title": "Status",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Monitor Types",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(monitor_status) by (monitor_type)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Response Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 20, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(monitor_response_time) by (monitor_name)",
     "legendFormat": "{{monitor_name}}"
    }
   ]
  },
  {
   "title": "Services",
   "type": "state-timeline",
   "gridPos": { "h": 31, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bool" } },
   "targets": [
    {
     "expr": "sum(monitor_status) by (monitor_type, monitor_name)",
     "legendFormat": "{{monitor_name}} ({{monitor_type}})"
    }
   ]
  }
 ]
}